      ******************************************************************
      *A.OR.S
      * QGECCAA: COMMAREA DE ARQUITECTURA DE APLICACIONES              *
      *                                                                *
      * AREA DE COMUNICACION ENTRE PROGRAMAS DE APLICACION             *
      * Y ARQUITECTURA                                                 *
      *A.OR.E
      *B.OR.S
      * QGECCAA: COMMAREA OF ARCHITECTURE OF APPLICATIONS              *
      *                                                                *
      * AREA OF COMUNICATION BETWEEN PROGRAMS OF APPLICATION           *
      * AND ARCHITECTURE                                               *
      *B.OR.E
      ******************************************************************
      *A.MF QGECCAA                   Qgeccaa                          *
      *A.MF QGECCAA-03                Qgeccaa-03                       *
      *A.MF DTA-GENERAL               Datos generales                  *
      *A.MF ENT-ACC                   Entidad contable                 *
      *A.MF 9-ENT-ACC                 Entidad contable                 *
      *A.MF CEN-ACCOUNT               Oficina contable                 *
      *A.MF 9-CEN-ACCOUNT             Oficina contable                 *
      *A.MF ACCO-NETNAME              Terminal red (netname, contable) *
      *A.MF ACCO-TERMINAL             Terminal CICS (EIBTRMID,         *
      *A/MF                           contable)                        *
      *A.MF DAT-ACCOUN                Fecha contable                   *
      *A.MF 9-DAT-ACCOUN              Fecha contable                   *
      *A.MF 2DAT-ACCOUN               Fecha contable db2               *
      *A.MF DAT-ED-ACCOU              Fecha contable editada           *
      *A.MF DAT-OPERAT                Fecha de operacion               *
      *A.MF 9-DAT-OPERAT              Fecha de operacion               *
      *A.MF 2DAT-OPERAT               Fecha de operacion db2           *
      *A.MF DAT-ED-OPERA              Fecha de operacion editada       *
      *A.MF DAT-TRANSMI               Fecha de transmision             *
      *A.MF 9-DAT-TRANSMI             Fecha de transmision             *
      *A.MF 2DAT-TRANSMI              Fecha de transmision db2         *
      *A.MF DAT-ED-TRANSM             Fecha de transmision editada     *
      *A.MF TIM-TRANSM                Hora de transmision              *
      *A.MF 9-TIM-TRANSM              Hora de transmision              *
      *A.MF TIM-ED-TRANS              Hora de transmision db2/editada  *
      *A.MF NETNAME                   Terminal red (netname, f­sico)   *
      *A.MF TERMINAL                  Terminal CICS (EIBTRMID, f­sico) *
      *A.MF USERID                    Usuario identificado al CICS     *
      *A.MF SW-SES                    Sesion: manana / tarde           *
      *A.FV   SW-MORNINGSESION        Sesion de manana                 *
      *A/FV                           'M'                              *
      *A.FV   SW-AFTERNSESION         Sesion de tarde                  *
      *A/FV                           'T'                              *
      *A.MF SW-TYPTRM                 Tipo de terminal                 *
      *A.FV   SW-TRM-4700-TERMI       Terminal 4700                    *
      *A/FV                           '11'                             *
      *A.FV   SW-TRM-5935-TERMI       Terminal 5935                    *
      *A/FV                           '12'                             *
      *A.FV   SW-TRM-3270-TERMI       Terminal 3270                    *
      *A/FV                           '20'                             *
      *A/FV                           '28'                             *
      *A/FV                           '29'                             *
      *A.FV   SW-TRM-PS1-TERMIN       Terminal PS 1 (PS / 2 Altamira)  *
      *A/FV                           '13'                             *
      *A.FV   SW-TRM-PS2-TERMIN       Terminal PS 2 (PS / 2 Ronda)     *
      *A/FV                           '14'                             *
      *A.FV   SW-TRM-PS3-TERMIN       Terminal PS 3 (PS / 2 Ico)       *
      *A/FV                           '15'                             *
      *A.FV   SW-TRM-PS4-TERMIN       Terminal PS 4 (PS / 2 Bct)       *
      *A/FV                           '17'                             *
      *A.FV   SW-TRM-PS5-TERMIN       Terminal PS 5 (PS / 2 Caixa      *
      *A/FV                           Catalunya)                       *
      *A/FV                           '18'                             *
      *A.FV   SW-TRM-PS6-TERMIN       Terminal PS 6 (PS / 2            *
      *A/FV                           Foundation / Atenea)             *
      *A/FV                           '19'                             *
      *A/FV                           '21'                             *
      *A.FV   SW-TRM-ATENEA-TERMI     Terminal PS / 2 Atenea           *
      *A/FV                           '21'                             *
      *A.FV   SW-TRM-PS8-TERMIN       Terminal PS / 8 Web Cliente      *
      *A/FV                           '25'                             *
      *A.FV   SW-TRM-PS9-TERMIN       Terminal PS / 9 X-Platform       *
      *A/FV                           '26'                             *
      *A.FV   SW-TRM-PS-TERMI         Terminal PS                      *
      *A/FV                           '13'                             *
      *A/FV                           '14'                             *
      *A/FV                           '15'                             *
      *A/FV                           '16'                             *
      *A/FV                           '17'                             *
      *A/FV                           '18'                             *
      *A/FV                           '19'                             *
      *A/FV                           '21'                             *
      *A/FV                           '25'                             *
      *A/FV                           '26'                             *
      *A.FV   SW-TRM-VIDEOTEX-TERMI   Terminal Videotex                *
      *A/FV                           '16'                             *
      *A.FV   SW-TRM-INPUNIV-TERM     Terminal universidad entrada     *
      *A/FV                           '35'                             *
      *A.FV   SW-TRM-OUTUNIV-TERM     Terminal universidad salida      *
      *A/FV                           '36'                             *
      *A.FV   SW-TRM-UNIV-TERMI       Terminal universidad             *
      *A/FV                           '35'                             *
      *A/FV                           '36'                             *
      *A.FV   SW-TRM-ATM1-TERMINA     Terminal cajero                  *
      *A/FV                           '40'                             *
      *A.FV   SW-1-TRM-NASB-TERM      Terminal CECA                    *
      *A/FV                           '41'                             *
      *A.FV   SW-2-TRM-NASB-TERM      Terminal CECA                    *
      *A/FV                           '42'                             *
      *A.FV   SW-TRM-NASB-TERMI       Terminal CECA                    *
      *A/FV                           '41'                             *
      *A/FV                           '42'                             *
      *A.FV   SW-TRM-POS-TERMI        Terminal punto de venta          *
      *A/FV                           '43'                             *
      *A.FV   SW-TRM-INPKRN-TERM      Terminal Corona entrada          *
      *A/FV                           '44'                             *
      *A.FV   SW-TRM-OUTKRN-TERM      Terminal Corona salida           *
      *A/FV                           '45'                             *
      *A.FV   SW-TRM-PARMKRN-TER      Terminal Corona parametros       *
      *A/FV                           '52'                             *
      *A.FV   SW-TRM-KORONA-TERMI     Terminal Corona                  *
      *A/FV                           '44'                             *
      *A/FV                           '45'                             *
      *A/FV                           '52'                             *
      *A.FV   SW-TRM-ISSSSPM-TERMI    Terminal SEMP emisor             *
      *A/FV                           '46'                             *
      *A.FV   SW-TRM-ACQSSPM-TERMI    Terminal SEMP adquiriente        *
      *A/FV                           '47'                             *
      *A.FV   SW-TRM-RECVSSPM-TERM    Terminal SEMP recibir ficheros   *
      *A/FV                           '48'                             *
      *A.FV   SW-TRM-UPDSSPM-TERMI    Terminal SEMP actualizar         *
      *A/FV                           ficheros                         *
      *A/FV                           '49'                             *
      *A.FV   SW-TRM-FICSSPM-TERM     Terminal SEMP ficticios          *
      *A/FV                           '50'                             *
      *A.FV   SW-TRM-SSPM-TERMI       Terminal SEMP                    *
      *A/FV                           '46'                             *
      *A/FV                           '47'                             *
      *A/FV                           '48'                             *
      *A/FV                           '49'                             *
      *A/FV                           '50'                             *
      *A.FV   SW-TRM-INPUT-TERMINA    Terminal entrada                 *
      *A/FV                           '53'                             *
      *A.FV   SW-TRM-REAL4B-TERMIN    Terminal 4B real                 *
      *A/FV                           '54'                             *
      *A.FV   SW-TRM-FIC4B-TERMIN     Terminal 4B ficticio             *
      *A/FV                           '55'                             *
      *A.FV   SW-TRM-4B-TERMI         Terminal 4B                      *
      *A/FV                           '54'                             *
      *A/FV                           '55'                             *
      *A.FV   SW-TRM-ATMLINK24-TERM   Link24 ATM virtual               *
      *A/FV                           '56'                             *
      *A.FV   SW-TRM-POSLINK24-TERM   Link24 POS virtual               *
      *A/FV                           '57'                             *
      *A.FV   SW-TRM-EXTNNETLINK24T   Link24 EXNET virtual             *
      *A/FV                           '58'                             *
      *A.FV   SW-TRM-OUTINK24-TERMI   Link24 OUT virtual               *
      *A/FV                           '59'                             *
      *A.FV   SW-TRM-LINK24-TERMI     Link24                           *
      *A/FV                           '56'                             *
      *A/FV                           '57'                             *
      *A/FV                           '58'                             *
      *A/FV                           '59'                             *
      *A.FV   SW-TRM-TAVETERMINALTY   Terminal TAVE                    *
      *A/FV                           '60'                             *
      *A.FV   SW-TRM-INPPOLCARD-TERM  Terminal POLCARD input           *
      *A/FV                           '61'                             *
      *A.FV   SW-TRM-VIRPOLCARD-TERM  Terminal POLCARD virtual         *
      *A/FV                           '62'                             *
      *A.FV   SW-TRM-OUTPOLCARD-TERM  Terminal POLCARD output          *
      *A/FV                           '63'                             *
      *A.FV   SW-TRM-POLCARD-TERMI    Terminal POLCARD                 *
      *A/FV                           '61'                             *
      *A/FV                           '62'                             *
      *A/FV                           '63'                             *
      *A.FV   SW-TRM-AUTCEN-TERMINAL  Terminal centro autorizado       *
      *A/FV                           '40'                             *
      *A/FV                           '41'                             *
      *A/FV                           '42'                             *
      *A/FV                           '43'                             *
      *A/FV                           '44'                             *
      *A/FV                           '45'                             *
      *A/FV                           '46'                             *
      *A/FV                           '47'                             *
      *A/FV                           '48'                             *
      *A/FV                           '49'                             *
      *A/FV                           '50'                             *
      *A/FV                           '52'                             *
      *A/FV                           '53'                             *
      *A/FV                           '54'                             *
      *A/FV                           '55'                             *
      *A/FV                           '61'                             *
      *A/FV                           '62'                             *
      *A/FV                           '63'.                            *
      *A/FV                           '61'                             *
      *A/FV                           '62'                             *
      *A/FV                           '63'                             *
      *A.MF CICS                      Identificador del cics           *
      *A.MF COD-TRA                   Codigo de transaccion            *
      *A.MF SW-TYP-PROCE              Tipo de proceso                  *
      *A.FV   SW-PRO-ONLINE-PROCES    Online                           *
      *A/FV                           'O'                              *
      *A.FV   SW-PRO-AUTHORIZ-PROC    Autorizacion                     *
      *A/FV                           'A'                              *
      *A.FV   SW-PRO-TELEDISK-PROC    Teledisco                        *
      *A/FV                           'T'                              *
      *A.FV   SW-PRO-OFFLINE-PROC     Offline                          *
      *A/FV                           'F'                              *
      *A.MF SW-APPSTATUS              Estado de la aplicacion          *
      *A.FV   SW-APP-AC               Activa                           *
      *A/FV                           'A'                              *
      *A.FV   SW-APP-INACT            Desactiva                        *
      *A/FV                           'D'                              *
      *A.FV   SW-APP-SESCHANGE        En cambio de sesion              *
      *A/FV                           'C'                              *
      *A.FV   SW-APP-RETRIEVA         En recuperacion                  *
      *A/FV                           'R'                              *
      *A.MF NUM-RETRYDB2LO            Numero de reintentos en bloqueo  *
      *A/MF                           db2                              *
      *A.MF NUM-SEQUE                 Numero de secuencia en la        *
      *A/MF                           transmision en terminal          *
      *A.MF 9-NUM-SEQUE               Numero de secuencia en la        *
      *A/MF                           transmision en terminal          *
      *A.MF GATAPB-VERS               Version gat/apb                  *
      *A.MF SW-LNG-TERM               Codigo de idioma del             *
      *A/MF                           terminalista                     *
      *A.FV   SW-TER-LNGNOTHI         Nada                             *
      *A/FV                           ''                               *
      *A.FV   SW-TER-LANGUA1          Espanol                          *
      *A/FV                           'E'                              *
      *A.FV   SW-TER-LANGUA2          Catal n                          *
      *A/FV                           'C'                              *
      *A.FV   SW-TER-LANGUA3          Gallego                          *
      *A/FV                           'G'                              *
      *A.FV   SW-TER-LANGUA4          Ingl‚s                           *
      *A/FV                           'I'                              *
      *A.FV   SW-TER-LANGUA5          Frances                          *
      *A/FV                           'F'                              *
      *A.FV   SW-TER-LANGUA6          Polaco                           *
      *A/FV                           'P'                              *
      *A.MF SW-A1-APPSTA              Estado de la divisa para la      *
      *A/MF                           aplicacion                       *
      *A.FV   SW-APP-SNGF             Monodivisa (entidad por defecto) *
      *A/FV                           'N'                              *
      *A.FV   SW-APP-CONV             Monodivisa convertida (entidad)  *
      *A/FV                           'C'                              *
      *A.FV   SW-APP-SNGR             Monodivisa (euros)               *
      *A/FV                           'E'                              *
      *A.FV   SW-APP-DOUB             Bidivisa (entidad + euros)       *
      *A/FV                           'B'                              *
      *A.FV   SW-APP-WTHT             Multidivisa (sin euros)          *
      *A/FV                           'S'                              *
      *A.FV   SW-APP-CPLT             Multidivisa completa (ent. +     *
      *A/FV                           euros)                           *
      *A/FV                           'M'                              *
      *A.FV   SW-APP-NENT             Multidivisa (sin divisa entidad) *
      *A/FV                           'X'                              *
      *A.MF SW-TRMMODEL               Modelo de terminal               *
      *A.FV   SW-TRM-INTERNETMOD      Internet                         *
      *A/FV                           'IN'                             *
      *A.FV   SW-TRM-MUSEUMMOD        Museos                           *
      *A/FV                           'MU'                             *
      *A.FV   SW-TRM-UPDATEMODEL      Actualizacion                    *
      *A/FV                           'AC'                             *
      *A.FV   SW-TRM-TELEPHONMOD      Telefono                         *
      *A/FV                           'TE'                             *
      *A.MF APPLICATION               Codigo de aplicacion             *
      *A.MF COD-MULTTRNS              Codigo de transaccion multiple   *
      *A.MF FILLER                    FILLER                           *
      *A.IF DTA-INPUTTRM              Datos de entrada de terminal     *
      *A.IF PRKEY                     Tecla pulsada                    *
      *A.MF SW-CSH                    Tipo de operacion de caja        *
      *A/MF                           utilizado                        *
      *A.FV   SW-A-USECSH             Tipo de operacion de caja a      *
      *A/FV                           'A'                              *
      *A.FV   SW-B-USECSH             Tipo de operacion de caja b      *
      *A/FV                           'B'                              *
      *A.MF SW-MODP                   Modificacion datos en panel de   *
      *A/MF                           entrada                          *
      *A.FV   SW-MOD-PANLYE           Si ha habido modificaciones      *
      *A/FV                           'S'                              *
      *A.FV   SW-MOD-PANLNO           No ha habido modificaciones      *
      *A/FV                           'N'                              *
      *A.FV   SW-MOD-PANLNOTH         No procede. Entrada distinta a   *
      *A/FV                           salida                           *
      *A/FV                           ''                               *
      *A.IF PNT-INPCPY                Apuntador mapa datos de          *
      *A/IF                           pantalla de entr./salida         *
      *A.IF SW-PA                     Informa si el terminal tiene     *
      *A/IF                           papel o no                       *
      *A.FV   SW-YES-PAPE             Si tiene papel                   *
      *A/FV                           'S'                              *
      *A.FV   SW-NO-PAPER             No tiene papel                   *
      *A/FV                           'N'                              *
      *A.IF FCC-INPOPE                Codigo de divisa de operacion    *
      *A/IF                           de entrada                       *
      *A.IF SW-TYP-INP                Tipo de entrada                  *
      *A.FV   SW-INP-BMSM             Tipo de mapa bms                 *
      *A/FV                           'B'                              *
      *A.FV   SW-INP-CPYTY            Tipo de copia                    *
      *A/FV                           'C'                              *
      *A/FV                           'G'                              *
      *A.FV   SW-INP-LESS-2K-CPYTY    Tipo de copia (menos 2k)         *
      *A/FV                           'C'                              *
      *A.FV   SW-INP-MORE2KCPYTY      Tipo de copia (mas 2k)           *
      *A/FV                           'G'                              *
      *A.IF FILLER                    FILLER                           *
      *A.MF AUTHORIZATIO              Autorizaciones (entrada/salida)  *
      *A.MF TB-AUTH                   Autorizaciones                   *
      *A.MF TB-RE-AUT                 Autorizaciones                   *
      *A.MF TB-AUT-ERR                Codigo de error que se desea     *
      *A/MF                           autorizar                        *
      *A.MF TB-AUT-STATUS             Situacion que se desea autorizar *
      *A.MF SW-AUTOR                  Indicador: error pendiente de    *
      *A/MF                           autorizacion                     *
      *A.FV   SW-AUT-PENDYES          Pendiente de autorizar           *
      *A/FV                           'S'                              *
      *A.FV   SW-AUT-PENDINO          No esta pendiente de autorizar   *
      *A/FV                           'N'                              *
      *A/FV                           ' '                              *
      *A.MF AMT-AUTHORIZ              Importe pendiente de autorizar   *
      *A.MF AUTREFEREN                Referencia de la operacion       *
      *A/MF                           segun aplicacion                 *
      *A.MF SW-ERR-AUT-ALN            Error en la autorizacion alnova  *
      *A.FV   SW-ERR-AUT-YESALNOVA    Si error en la validacion        *
      *A/FV                           usuario/password de la           *
      *A/FV                           autorizacion                     *
      *A/FV                           'S'                              *
      *A.MF FILLER                    FILLER                           *
      *A.OF AUXAUTHORIZATION          Autorizaciones (puntero de       *
      *A/OF                           salida)                          *
      *A.OF SEQNUM                    Numero de secuencia de la        *
      *A/OF                           autorizacion                     *
      *A.OF 1-SEQNUM                  Numero de secuencia de la        *
      *A/OF                           autorizacion                     *
      *A.OF AUTHPNT                   Puntero a datos de               *
      *A/OF                           autorizaciones                   *
      *A.OF 1-AUTHPNT                 Puntero a datos de               *
      *A/OF                           autorizaciones                   *
      *A.MF CONVERS                   Datos de conversacion            *
      *A/MF                           (entrada/salida)                 *
      *A.MF SW-STA                    Estado                           *
      *A.FV   SW-BEGINNING-STA        Inicio                           *
      *A/FV                           'I'                              *
      *A.FV   SW-CONTINUAT-STA        Continuacion                     *
      *A/FV                           'C'                              *
      *A.FV   SW-CONFIRMAT-STA        Confirmacion                     *
      *A/FV                           'X'                              *
      *A.MF CASE                      Caso para la aplicacion          *
      *A.MF ADATA                     Datos propios de la aplicacion   *
      *A.MF A1-DTA-AP                 Datos propios de la aplicacion   *
      *A.MF FILLER                    FILLER                           *
      *A.MF DYNAMREPORT               Datos utilizados por el listado  *
      *A/MF                           dinamico de tablas               *
      *A.MF DES-TBL                   Nombre de la tabla para el       *
      *A/MF                           listado dinamico                 *
      *A.MF POSITION-COM              Posicion dentro de la commarea   *
      *A/MF                           de la aplicacion para la         *
      *A/MF                           sentencia where                  *
      *A.MF LENGTH-COMMA              Longitud dentro de la commarea   *
      *A/MF                           de la aplicacion para la         *
      *A/MF                           sentencia where                  *
      *A.MF LNG-TBLDYCRP              Idioma de la tabla para el       *
      *A/MF                           listado dinamico                 *
      *A.MF DTA-LTH                   Longitud datos propios           *
      *A/MF                           adicionales de la aplicacion     *
      *A.MF DTA-PNT                   Puntero de datos propios         *
      *A/MF                           adicionales de la aplicacion     *
      *A.MF SW-EXTNNTWK               Operacion con red externa        *
      *A.FV   SW-EXT-NTWKYES          Si operacion con red externa     *
      *A/FV                           'S'                              *
      *A.MF PNT-INT-MSG               Puntero a mensaje interno        *
      *A.MF SW-PNT-INTMSG             Puntero a mensaje interno        *
      *A.FV   SW-PNT-EMPTY-MSG        Puntero a mensaje vacio          *
      *A/FV                           HIGH-VALUES                      *
      *A.MF PNT-NOALN                 Puntero para datos no altamira   *
      *A.MF FILLER                    FILLER                           *
      *A.MF DTA-NEXTTRN               Datos de siguiente transaccion   *
      *A.MF SW-NEXTTRNS               Codigo de transaccion a pasarle  *
      *A/MF                           el control                       *
      *A.FV   SW-NEX-LASTNEXTTRNS     A la ultima que nos dio el       *
      *A/FV                           control                          *
      *A/FV                           'ULTI'                           *
      *A.FV   SW-NEX-SAMENEXTTRNS     A la misma                       *
      *A/FV                           'SAME'                           *
      *A.FV   SW-NEX-MENUNEXTTRNS     Al menu principal                *
      *A/FV                           'MENU'                           *
      *A.FV   SW-NEX-EMPTYNEXTTRNS    A ninguna                        *
      *A/FV                           SPACES                           *
      *A.MF SW-AUTOMAT                Indica si la siguiente           *
      *A/MF                           transaccion se arranca automat.  *
      *A.FV   SW-AUT-ROLLOUTYE        Si arranque automatico           *
      *A/FV                           'S'                              *
      *A.FV   SW-AUT-ROLLOUTNO        No arranque automatico           *
      *A/FV                           'N'                              *
      *A/FV                           ' '                              *
      *A.IF SW-ACT                    Accion                           *
      *A.FV   SW-88-PROGRAMACTIO      Programa                         *
      *A/FV                           'PRG'                            *
      *A.FV   SW-88-TERMINALACTI      Terminal                         *
      *A/FV                           'TER'                            *
      *A/FV                           ' '                              *
      *A.IF SW-CHA                    Cadena                           *
      *A.FV   SW-BEGINNING-CHA        Cadena inicio                    *
      *A/FV                           'I'                              *
      *A.FV   SW-ADDITIONA-CHA        Anadir a cadena                  *
      *A/FV                           'A'                              *
      *A.IF CHAICASE                  Caso al moverse en la cadena     *
      *A.IF DATA-CHAI                 Datos propios de la aplicacion   *
      *A/IF                           usados para moverse a trav‚s de  *
      *A/IF                           la cadena                        *
      *A.OF OUT-TERMINA               Datos de la salida del terminal  *
      *A.OF SW-ERRCOD                 Codigo de error                  *
      *A.FV   SW-ERR-EMPTYERRCOD      No hay codigo de error           *
      *A/FV                           SPACES                           *
      *A.OF SW-COD-WA1                Codigo de aviso 1                *
      *A.FV   SW-WAR-EMPTWARNCOD1     No hay codigo de aviso 1         *
      *A/FV                           SPACES                           *
      *A.OF SW-COD-WA2                Codigo de aviso 2                *
      *A.FV   SW-WAR-EMPTWARNCOD2     No hay codigo de aviso 2         *
      *A/FV                           SPACES                           *
      *A.OF ERR-VARIA1                Variable 1 a incluir en mensaje  *
      *A/OF                           error                            *
      *A.OF ERR-VARIA2                Variable 2 a incluir en mensaje  *
      *A/OF                           error                            *
      *A.OF WARN1VARIA1               Variable 1 a incluir en mensaje  *
      *A/OF                           aviso 1                          *
      *A.OF WARN1VARIA2               Variable 2 a incluir en mensaje  *
      *A/OF                           aviso 1                          *
      *A.OF WARN2VARIA1               Variable 1 a incluir en mensaje  *
      *A/OF                           aviso 2                          *
      *A.OF WARN2VARIA2               Variable 2 a incluir en mensaje  *
      *A/OF                           aviso 2                          *
      *A.OF AMT-DISPENSE              Importe del dispensador          *
      *A.OF LOCAL-EJOURN              Campo a actualizar en diario     *
      *A/OF                           electronico local                *
      *A.OF SW-TYP-OUTP               Pantalla a enviar al terminal    *
      *A.FV   SW-OUT-TYP-INPUTSC      La de entrada                    *
      *A/FV                           'E'                              *
      *A.FV   SW-OUT-TYP-OUTPUTS      La de salida                     *
      *A/FV                           'S'                              *
      *A.FV   SW-OUT-TYP-ARCSCRL      Paginacion de arquitectura       *
      *A/FV                           'P'                              *
      *A.FV   SW-OUT-TYP-COPYSCRE     Salida copy fija no bms          *
      *A/FV                           'C'                              *
      *A.FV   SW-OUT-TYP-NONESC       Ninguna                          *
      *A/FV                           ''                               *
      *A.OF OUT-COPY                  Nombre de copy salida            *
      *A.OF OUT-PANEL                 Nombre panel BMS de salida       *
      *A.OF TB-DESTI                  Informacion de salidas destino   *
      *A/OF                           terminal                         *
      *A.OF TB-RE-DEST                Informacion de salidas destino   *
      *A/OF                           terminal                         *
      *A.OF TB-DES1                   Prefijo TS contiene la salida    *
      *A.OF TB-SCRDOCU                Indicador destino (pantalla /    *
      *A/OF                           documento)                       *
      *A.OF TB-DOCNUM                 Numero de documento              *
      *A.OF TB-FSTLINDOC              Posicion de la primera linea a   *
      *A/OF                           documento                        *
      *A.OF TB-9-FSTLINDOC            Posicion de la primera linea a   *
      *A/OF                           documento                        *
      *A.OF TB-FORM                   Codigo de impreso de salida      *
      *A.OF TB-DISKP                  Disco de fichero a grabar en ps  *
      *A.OF TB-DES-DES-FIL            Nombre de fichero a grabar en ps *
      *A.OF TB-DES-FILEUSE            Uso de fichero a grabar en ps    *
      *A.OF TB-LNG                    Codigo de idioma de salida       *
      *A.IF DTA-SCR                   Datos para la gestion de la      *
      *A/IF                           paginacion                       *
      *A.IF DTA-CONT                  Contenido generico del listado   *
      *A.IF TB-ALLWSELEC              Digitos a admitir como campo de  *
      *A/IF                           seleccion                        *
      *A.IF TB-RE-ALLWSELE            Digitos a admitir como campo de  *
      *A/IF                           seleccion                        *
      *A.IF TB-ALL-SEL                Digitos a admitir como campo de  *
      *A/IF                           seleccion                        *
      *A.IF SW-VRSSELE                Indicador de multiseleccion      *
      *A/IF                           permitida                        *
      *A.FV   SW-VRS-SELECTYES        Se permite selc. De varias       *
      *A/FV                           lineas                           *
      *A/FV                           'S'                              *
      *A.FV   SW-VRS-SELECTINO        No se permite selc. De varias    *
      *A/FV                           lineas                           *
      *A/FV                           'N'                              *
      *A.IF FIXEDMARGIN               Margen a mantener en desplaz.    *
      *A/IF                           Izquierda                        *
      *A.IF 9-FIXEDMARGIN             Margen a mantener en desplaz.    *
      *A/IF                           Izquierda                        *
      *A.IF T-PF                      Teclas de funcion permitidas     *
      *A.IF T-RE-P                    Teclas de funcion permitidas     *
      *A.IF T-NUM-PF                  Numero de la tecla permitida     *
      *A.IF T-TXT-PF                  Literal de tecla a mostrar en    *
      *A/IF                           panel                            *
      *A.IF T-SEL-PF                  Tecla de funcion de seleccion    *
      *A.IF SW-ADVPAG                 Ind. De devolver control al      *
      *A/IF                           listado con pf8                  *
      *A.FV   SW-ADV-ADVPAGYE         Se devuelve control              *
      *A/FV                           'S'                              *
      *A.FV   SW-ADV-ADVPAGNO         No se devuelve control           *
      *A/FV                           'N'                              *
      *A/FV                           ' '                              *
      *A.IF SW-FLG-DTAMO              Ind. De modificacion de linea    *
      *A/IF                           de datos                         *
      *A.FV   SW-DTA-YESALLWMODI      Se permite la modif.             *
      *A/FV                           'S'                              *
      *A.FV   SW-DTA-NOALLWMODIF      No se permite la modif.          *
      *A/FV                           'N'                              *
      *A.IF SCREENLINE                Linea de pantalla usado por el   *
      *A/IF                           programa de gestion de ts        *
      *A.IF SCREENCOLU                Columna de pantalla usado por    *
      *A/IF                           el programa de gestion de ts     *
      *A.IF NUM-HEALINE               Numero de linea fijas de         *
      *A/IF                           cabecera                         *
      *A.IF 9-NUM-HEALINE             Numero de linea fijas de         *
      *A/IF                           cabecera                         *
      *A.IF SW-FLG-LTRSCRL            Indicador de scroll literal      *
      *A.FV   SW-LTR-SCRLLTRYE        Se realiza scroll lateral        *
      *A/FV                           'S'                              *
      *A/FV                           ' '                              *
      *A.FV   SW-LTR-SCRLLTRNO        No se realiza scroll lateral     *
      *A/FV                           'N'                              *
      *A.IF NUM-SELECTITEM            Numero de item seleccionado      *
      *A.IF NUM-MAXLST                Numero maximo de item a listar   *
      *A/IF                           en gts                           *
      *A.IF SW-FLG-HEADVAR            Indicador de variable de         *
      *A/IF                           cabecera                         *
      *A.FV   SW-HEA-YESHEADVAR       Si variable de cabecera          *
      *A/FV                           'S'                              *
      *A.FV   SW-HEA-NOHEADVARI       No variable de cabecera          *
      *A/FV                           'N'                              *
      *A/FV                           ' '                              *
      *A.IF COPYGTSOUTP               Salida de la gts de la copy      *
      *A.IF SUFFIX-EDITION            Edicion del sufijo               *
      *A.IF SUFFIX-DATE               Sufijo de fecha                  *
      *A.IF SUFFIX-NUM                Sufijo de numero                 *
      *A.IF FILLER                    FILLER                           *
      *A.OF DTA-ANALI                 Salida de la aplicacion datos    *
      *A/OF                           para anal­tica y estadisticas    *
      *A.OF ENT-ANALITI               Entidad destino analitica        *
      *A.OF 9-ENT-ANALITI             Entidad destino analitica        *
      *A.OF CEN-ANALIT                Centro destino analitica         *
      *A.OF 9-CEN-ANALIT              Centro destino analitica         *
      *A.OF ANALITICPROD              Clave producto de la aplicacion  *
      *A.OF A1-ANALITICPRO            Clave producto de la aplicacion  *
      *A.OF ACC-ANALITI               Numero de cuenta                 *
      *A.OF COD-ANLSERV               Codigo de servicio               *
      *A.OF FILLER                    FILLER                           *
      *A.OF 1-ANALITIC-GROU           Grupo analitico                  *
      *A.OF CUS-ANALITI               Cliente                          *
      *A.OF AMT-ANALITI               Importe                          *
      *A.OF ANALITICSPR               Subproducto                      *
      *A.OF ANALITICPUR               Finalidad                        *
      *A.OF ANALITICCOLT              Garantia                         *
      *A.OF SUBCLASSIF                Sub-clasificacion de la          *
      *A/OF                           transaccion                      *
      *A.OF A2-ANALITIC               Grupo analitico                  *
      *A.OF SW-OPT                    Tipo de operacion realizada      *
      *A.FV   SW-OPE-TYPEREG          Alta                             *
      *A/FV                           'A'                              *
      *A.FV   SW-OPE-TYPEANN          Baja                             *
      *A/FV                           'B'                              *
      *A.FV   SW-OPE-TYPEMODI         Modificacion                     *
      *A/FV                           'M'                              *
      *A.FV   SW-OPE-TYPEINQUIRY      Consulta                         *
      *A/FV                           'C'                              *
      *A.FV   SW-OPE-TYPEISSOPE       Edicion                          *
      *A/FV                           'E'                              *
      *A.FV   SW-OPE-TYPEBTCHREQ      Peticion batch                   *
      *A/FV                           'P'                              *
      *A.FV   SW-OPE-TYPINPOUT        Operacion de entrada / salida    *
      *A/FV                           'O'                              *
      *A.FV   SW-OPE-TYPNOTH          Nada                             *
      *A/FV                           'N'                              *
      *A.FV   SW-OPE-TYPAUTFILTR      Transaccion transmision          *
      *A/FV                           automatica de ficheros           *
      *A/FV                           '1'                              *
      *A.FV   SW-OPE-TYPESBISTRNS     Transaccion sistema de           *
      *A/FV                           Intercambio entre Cajas de       *
      *A/FV                           Ahorro                           *
      *A/FV                           '2'                              *
      *A.FV   SW-OPE-TYPEACRUTRNS     Transaccion periodificada        *
      *A/FV                           '3'                              *
      *A.FV   SW-OPE-TYPEINQUTRNS     Transaccion consulta             *
      *A/FV                           '4'                              *
      *A.FV   SW-OPE-TYPEANNUTRNS     Transaccion anulacion            *
      *A/FV                           '5'                              *
      *A.FV   SW-OPE-TYPCANC          Cancelacion                      *
      *A/FV                           '6'                              *
      *A.OF SW-ACCOU                  Operacion contable               *
      *A.FV   SW-ACC-OPERYES          Operacion contable               *
      *A/FV                           'S'                              *
      *A.FV   SW-ACC-OPERANO          Operacion no contable            *
      *A/FV                           'N'                              *
      *A.OF DTA-APPLICA               Datos de libre uso para la       *
      *A/OF                           aplicacion                       *
      *A.IF 2-ANL-GROUP               Analitica                        *
      *A.IF A1-2-ANALI-GROUP          Area Altamira                    *
      *A.IF CHANN                     Canal                            *
      *A.MF SW-STTCOD                 Codigo de inicio                 *
      *A.FV   SW-STT-NOSYNCP          No syncpoint                     *
      *A/FV                           'D '                             *
      *A.FV   SW-STT-YESSYNC          Si syncpoint                     *
      *A/FV                           'DS'                             *
      *A.FV   SW-DPL                  Inicio por dpl                   *
      *A/FV                           'D '                             *
      *A/FV                           'DS'                             *
      *A.FV   SW-STT-TDQ              Cola td                          *
      *A/FV                           'QD'                             *
      *A.FV   SW-STT-WTHTDATASTT      Sin datos                        *
      *A/FV                           'S '                             *
      *A.FV   SW-STT-WITHDATASTT      Con datos                        *
      *A/FV                           'SD'                             *
      *A.FV   SW-FEPI                 Qcrmfepi                         *
      *A/FV                           'SZ'                             *
      *A.FV   SW-STT-TERM             Terminal                         *
      *A/FV                           'TD'                             *
      *A.FV   SW-STT-ALLOWEDSYNCPOIN  Syncpoint permitido              *
      *A/FV                           'DS'                             *
      *A/FV                           'QD'                             *
      *A/FV                           'S '                             *
      *A/FV                           'SD'                             *
      *A/FV                           'SZ'                             *
      *A/FV                           'TD'                             *
      *A.FV   SW-STT-NOALLOWEDSYNCPO Syncpoint no permitido           *
      *A/FV                           'D '                             *
      *A.IF LOGON-USERID              Usuario de conexion              *
      *A.IF SW-PREFORMAT              Preformatear                     *
      *A.FV   SW-PRE-YEPREFORMAT      Si preformateo                   *
      *A/FV                           'Y'                              *
      *A.FV   SW-PRE-NOPREFORMAT      No preformateo                   *
      *A/FV                           'N'                              *
      *A.OF SW-FLG-MGCAL              Indicador de alarma              *
      *A.FV   SW-MGC-NOMAGICALAR      No alarma                        *
      *A/FV                           '0'                              *
      *A.FV   SW-MGC-SALEMAGICALARM   Venta                            *
      *A/FV                           '1'                              *
      *A.FV   SW-MGC-THREATMAGICALARM Amenaza                          *
      *A/FV                           '2'                              *
      *A.FV   SW-MGC-GRACEPRDMAGICAL Carencia                         *
      *A/FV                           '3'                              *
      *A.OF SW-FLG-ANLPSBCH           Indicador anal­tico              *
      *A.FV   SW-ANL-PSB              Libreta                          *
      *A/FV                           'LIB'                            *
      *A.FV   SW-ANL-CHK              Cheque                           *
      *A/FV                           'CHE'                            *
      *A.OF EXCEPTION-TYPE1           Tipo de incidencia               *
      *A.OF FLG-ANALCHBK              Indicador de talonario analitico *
      *A.OF NUM-ANALCHBK              Numero de talonario analitico    *
      *A.OF SW-TYP-ANLCENTE           Tipo de centro analitico         *
      *A.FV   SW-ANL-BRNCENT-TYP      Oficina                          *
      *A/FV                           'O'                              *
      *A.FV   SW-ANL-ZONECEN-TYP      Zona                             *
      *A/FV                           'Z'                              *
      *A.FV   SW-ANL-RISKCENTER-TYP   Riesgo                           *
      *A/FV                           'I'                              *
      *A.FV   SW-ANL-REGCENT-TYP      Registro                         *
      *A/FV                           'R'                              *
      *A.OF SW-ANL-RISKAPRX           Aproximacion del riesgo          *
      *A/OF                           analitico                        *
      *A.FV   SW-RIS-YESAPRX          Aproximacion                     *
      *A/FV                           'S'                              *
      *A.FV   SW-RIS-PROPSUBMIT       Elevacion de propuesta           *
      *A/FV                           'E'                              *
      *A.OF ERR-INFORMATI             Informacion error                *
      *A.OF OBJECT-ERROR              Nombre del objeto donde se       *
      *A/OF                           produjo error                    *
      *A.OF SQLCODE                   Codigo de retorno del DB2        *
      *A.OF SQLERRM                   Informacion error DB2            *
      *A.OF EIBFN                     Ultima funcion CICS              *
      *A.OF EIBRSRCE                  Ultimo recurso CICS              *
      *A.OF EIBRCODE                  Codigo de respuesta al CICS      *
      *A.OF EIBRESP1                  Condicion producida por ultima   *
      *A/OF                           funcion CICS                     *
      *A.OF EIBRESP2                  Informacion adicional a EIBRESP1 *
      *A.OF FILLER                    FILLER                           *
      ******************************************************************
      ******************************************************************
      *B.MF QGECCAA                   Qgeccaa                          *
      *B.MF QGECCAA-03                Qgeccaa-03                       *
      *B.MF DTA-GENERAL               General data                     *
      *B.MF ENT-ACC                   Accounting entity                *
      *B.MF 9-ENT-ACC                 Accounting entity                *
      *B.MF CEN-ACCOUNT               Accounting branch                *
      *B.MF 9-CEN-ACCOUNT             Accounting branch                *
      *B.MF ACCO-NETNAME              Accounting netname               *
      *B.MF ACCO-TERMINAL             Accounting CICS terminal         *
      *B/MF                           (EIBTRMID)                       *
      *B.MF DAT-ACCOUN                Accounting date                  *
      *B.MF 9-DAT-ACCOUN              Accounting date                  *
      *B.MF 2DAT-ACCOUN               Db2 accounting date              *
      *B.MF DAT-ED-ACCOU              Issued accounting date           *
      *B.MF DAT-OPERAT                Operation date                   *
      *B.MF 9-DAT-OPERAT              Operation date                   *
      *B.MF 2DAT-OPERAT               Db2 operation date               *
      *B.MF DAT-ED-OPERA              Issued operation date            *
      *B.MF DAT-TRANSMI               Transmission date                *
      *B.MF 9-DAT-TRANSMI             Db2 transmission date            *
      *B.MF 2DAT-TRANSMI              Transmission date                *
      *B.MF DAT-ED-TRANSM             Issued transmission date         *
      *B.MF TIM-TRANSM                Transmission time                *
      *B.MF 9-TIM-TRANSM              Transmission time                *
      *B.MF TIM-ED-TRANS              Db2/issued transmission time     *
      *B.MF NETNAME                   Netname                          *
      *B.MF TERMINAL                  CICS terminal (EIBTRMID)         *
      *B.MF USERID                    CICS user identification         *
      *B.MF SW-SES                    Session: morning / afternoon     *
      *B.FV   SW-MORNINGSESION        Morning session                  *
      *B/FV                           'M'                              *
      *B.FV   SW-AFTERNSESION         Afternoon session                *
      *B/FV                           'T'                              *
      *B.MF SW-TYPTRM                 Terminal type                    *
      *B.FV   SW-TRM-4700-TERMI       Terminal 4700                    *
      *B/FV                           '11'                             *
      *B.FV   SW-TRM-5935-TERMI       Terminal 5935                    *
      *B/FV                           '12'                             *
      *B.FV   SW-TRM-3270-TERMI       Terminal 3270                    *
      *B/FV                           '20'                             *
      *B/FV                           '28'                             *
      *B/FV                           '29'                             *
      *B.FV   SW-TRM-PS1-TERMIN       Terminal PS 1 (PS / 2 Alnova)    *
      *B/FV                           '13'                             *
      *B.FV   SW-TRM-PS2-TERMIN       Terminal PS 2 (PS / 2 Ronda)     *
      *B/FV                           '14'                             *
      *B.FV   SW-TRM-PS3-TERMIN       Terminal PS 3 (PS / 2 Ico)       *
      *B/FV                           '15'                             *
      *B.FV   SW-TRM-PS4-TERMIN       Terminal PS 4 (PS / 2 Bct)       *
      *B/FV                           '17'                             *
      *B.FV   SW-TRM-PS5-TERMIN       Terminal PS 5 (PS / 2 entity)    *
      *B/FV                           '18'                             *
      *B.FV   SW-TRM-PS6-TERMIN       Terminal PS 6 (PS / 2            *
      *B/FV                           Foundation / Atenea)             *
      *B/FV                           '19'                             *
      *B/FV                           '21'                             *
      *B.FV   SW-TRM-ATENEA-TERMI     Terminal PS / 2 Atenea           *
      *B/FV                           '21'                             *
      *B.FV   SW-TRM-PS8-TERMIN       Terminal PS / 8 Web Customer     *
      *B/FV                           '25'                             *
      *B.FV   SW-TRM-PS9-TERMIN       Terminal PS / 9 X-Platform       *
      *B/FV                           '26'                             *
      *B.FV   SW-TRM-PS-TERMI         Terminal PS                      *
      *B/FV                           '13'                             *
      *B/FV                           '14'                             *
      *B/FV                           '15'                             *
      *B/FV                           '16'                             *
      *B/FV                           '17'                             *
      *B/FV                           '18'                             *
      *B/FV                           '19'                             *
      *B/FV                           '21'                             *
      *B/FV                           '25'                             *
      *B/FV                           '26'                             *
      *B.FV   SW-TRM-VIDEOTEX-TERMI   Terminal Videotex                *
      *B/FV                           '16'                             *
      *B.FV   SW-TRM-INPUNIV-TERM     University terminal, input       *
      *B/FV                           '35'                             *
      *B.FV   SW-TRM-OUTUNIV-TERM     University terminal, output      *
      *B/FV                           '36'                             *
      *B.FV   SW-TRM-UNIV-TERMI       University terminal              *
      *B/FV                           '35'                             *
      *B/FV                           '36'                             *
      *B.FV   SW-TRM-ATM1-TERMINA     ATM terminal                     *
      *B/FV                           '40'                             *
      *B.FV   SW-1-TRM-NASB-TERM      NASB terminal                    *
      *B/FV                           '41'                             *
      *B.FV   SW-2-TRM-NASB-TERM      NASB terminal                    *
      *B/FV                           '42'                             *
      *B.FV   SW-TRM-NASB-TERMI       NASB terminal                    *
      *B/FV                           '41'                             *
      *B/FV                           '42'                             *
      *B.FV   SW-TRM-POS-TERMI        POS                              *
      *B/FV                           '43'                             *
      *B.FV   SW-TRM-INPKRN-TERM      Corona terminal, input           *
      *B/FV                           '44'                             *
      *B.FV   SW-TRM-OUTKRN-TERM      Corona terminal, output          *
      *B/FV                           '45'                             *
      *B.FV   SW-TRM-PARMKRN-TER      Corona terminal, parameters      *
      *B/FV                           '52'                             *
      *B.FV   SW-TRM-KORONA-TERMI     Corona terminal                  *
      *B/FV                           '44'                             *
      *B/FV                           '45'                             *
      *B/FV                           '52'                             *
      *B.FV   SW-TRM-ISSSSPM-TERMI    SSPM terminal, issuer            *
      *B/FV                           '46'                             *
      *B.FV   SW-TRM-ACQSSPM-TERMI    SSPM terminal, acquier           *
      *B/FV                           '47'                             *
      *B.FV   SW-TRM-RECVSSPM-TERM    SSPM terminal receive files      *
      *B/FV                           '48'                             *
      *B.FV   SW-TRM-UPDSSPM-TERMI    SSPM terminal updtate files      *
      *B/FV                           '49'                             *
      *B.FV   SW-TRM-FICSSPM-TERM     SSPM terminal, fictitious        *
      *B/FV                           '50'                             *
      *B.FV   SW-TRM-SSPM-TERMI       SSPM terminal                    *
      *B/FV                           '46'                             *
      *B/FV                           '47'                             *
      *B/FV                           '48'                             *
      *B/FV                           '49'                             *
      *B/FV                           '50'                             *
      *B.FV   SW-TRM-INPUT-TERMINA    Input terminal                   *
      *B/FV                           '53'                             *
      *B.FV   SW-TRM-REAL4B-TERMIN    Real 4B terminal                 *
      *B/FV                           '54'                             *
      *B.FV   SW-TRM-FIC4B-TERMIN     Fictitious 4B terminal           *
      *B/FV                           '55'                             *
      *B.FV   SW-TRM-4B-TERMI         4B terminal                      *
      *B/FV                           '54'                             *
      *B/FV                           '55'                             *
      *B.FV   SW-TRM-ATMLINK24-TERM   Link24 ATM virtual               *
      *B/FV                           '56'                             *
      *B.FV   SW-TRM-POSLINK24-TERM   Link24 POS virtual               *
      *B/FV                           '57'                             *
      *B.FV   SW-TRM-EXTNNETLINK24T   Link24 EXNET virtual             *
      *B/FV                           '58'                             *
      *B.FV   SW-TRM-OUTINK24-TERMI   Link24 OUT virtual               *
      *B/FV                           '59'                             *
      *B.FV   SW-TRM-LINK24-TERMI     Link24                           *
      *B/FV                           '56'                             *
      *B/FV                           '57'                             *
      *B/FV                           '58'                             *
      *B/FV                           '59'                             *
      *B.FV   SW-TRM-TAVETERMINALTY   Terminal TAVE                    *
      *B/FV                           '60'                             *
      *B.FV   SW-TRM-INPPOLCARD-TERM  Terminal POLCARD input           *
      *B/FV                           '61'                             *
      *B.FV   SW-TRM-VIRPOLCARD-TERM  Terminal POLCARD virtual         *
      *B/FV                           '62'                             *
      *B.FV   SW-TRM-OUTPOLCARD-TERM  Terminal POLCARD output          *
      *B/FV                           '63'                             *
      *B.FV   SW-TRM-POLCARD-TERMI    Terminal POLCARD                 *
      *B/FV                           '61'                             *
      *B/FV                           '62'                             *
      *B/FV                           '63'                             *
      *B.FV   SW-TRM-AUTCEN-TERMINAL  Authorized center terminal       *
      *B/FV                           '40'                             *
      *B/FV                           '41'                             *
      *B/FV                           '42'                             *
      *B/FV                           '43'                             *
      *B/FV                           '44'                             *
      *B/FV                           '45'                             *
      *B/FV                           '46'                             *
      *B/FV                           '47'                             *
      *B/FV                           '48'                             *
      *B/FV                           '49'                             *
      *B/FV                           '50'                             *
      *B/FV                           '52'                             *
      *B/FV                           '53'                             *
      *B/FV                           '54'                             *
      *B/FV                           '55'                             *
      *B/FV                           '61'                             *
      *B/FV                           '62'                             *
      *B/FV                           '63'.                            *
      *B/FV                           '61'                             *
      *B/FV                           '62'                             *
      *B/FV                           '63'                             *
      *B.MF CICS                      Cics identifier                  *
      *B.MF COD-TRA                   Transaction code                 *
      *B.MF SW-TYP-PROCE              Process type                     *
      *B.FV   SW-PRO-ONLINE-PROCES    Online                           *
      *B/FV                           'O'                              *
      *B.FV   SW-PRO-AUTHORIZ-PROC    Authorization                    *
      *B/FV                           'A'                              *
      *B.FV   SW-PRO-TELEDISK-PROC    Teledisk                         *
      *B/FV                           'T'                              *
      *B.FV   SW-PRO-OFFLINE-PROC     Offline                          *
      *B/FV                           'F'                              *
      *B.MF SW-APPSTATUS              Application status               *
      *B.FV   SW-APP-AC               Active                           *
      *B/FV                           'A'                              *
      *B.FV   SW-APP-INACT            Inactive                         *
      *B/FV                           'D'                              *
      *B.FV   SW-APP-SESCHANGE        Session change                   *
      *B/FV                           'C'                              *
      *B.FV   SW-APP-RETRIEVA         Retrieval                        *
      *B/FV                           'R'                              *
      *B.MF NUM-RETRYDB2LO            Retries number in db2 lock       *
      *B.MF NUM-SEQUE                 Sequence number on terminal      *
      *B/MF                           transmission                     *
      *B.MF 9-NUM-SEQUE               Sequence number on terminal      *
      *B/MF                           transmission                     *
      *B.MF GATAPB-VERS               Gat/apb version                  *
      *B.MF SW-LNG-TERM               Language code of terminal user   *
      *B.FV   SW-TER-LNGNOTHI         Nothing                          *
      *B/FV                           ''                               *
      *B.FV   SW-TER-LANGUA1          Language 1                       *
      *B/FV                           'E'                              *
      *B.FV   SW-TER-LANGUA2          Language 2                       *
      *B/FV                           'C'                              *
      *B.FV   SW-TER-LANGUA3          Language 3                       *
      *B/FV                           'G'                              *
      *B.FV   SW-TER-LANGUA4          Language 4                       *
      *B/FV                           'I'                              *
      *B.FV   SW-TER-LANGUA5          Language 5                       *
      *B/FV                           'F'                              *
      *B.FV   SW-TER-LANGUA6          Language 6                       *
      *B/FV                           'P'                              *
      *B.MF SW-A1-APPSTA              Currency status for application  *
      *B.FV   SW-APP-SNGF             Single currency (entity by       *
      *B/FV                           default)                         *
      *B/FV                           'N'                              *
      *B.FV   SW-APP-CONV             Converted single currency        *
      *B/FV                           (entity)                         *
      *B/FV                           'C'                              *
      *B.FV   SW-APP-SNGR             Single currency (euros)          *
      *B/FV                           'E'                              *
      *B.FV   SW-APP-DOUB             Double currency (entity + euros) *
      *B/FV                           'B'                              *
      *B.FV   SW-APP-WTHT             Multi-currency (without euros)   *
      *B/FV                           'S'                              *
      *B.FV   SW-APP-CPLT             Complete multi-currency (ent. +  *
      *B/FV                           euros)                           *
      *B/FV                           'M'                              *
      *B.FV   SW-APP-NENT             Multi-currency (without entity   *
      *B/FV                           currency)                        *
      *B/FV                           'X'                              *
      *B.MF SW-TRMMODEL               Terminal model                   *
      *B.FV   SW-TRM-INTERNETMOD      Internet                         *
      *B/FV                           'IN'                             *
      *B.FV   SW-TRM-MUSEUMMOD        Museums                          *
      *B/FV                           'MU'                             *
      *B.FV   SW-TRM-UPDATEMODEL      Updating                         *
      *B/FV                           'AC'                             *
      *B.FV   SW-TRM-TELEPHONMOD      Telephone                        *
      *B/FV                           'TE'                             *
      *B.MF APPLICATION               Application code                 *
      *B.MF COD-MULTTRNS              Multiple transaction code        *
      *B.MF FILLER                    FILLER                           *
      *B.IF DTA-INPUTTRM              Terminal input data              *
      *B.IF PRKEY                     Pressed key                      *
      *B.MF SW-CSH                    Cash operation type used         *
      *B.FV   SW-A-USECSH             Cash operation type a            *
      *B/FV                           'A'                              *
      *B.FV   SW-B-USECSH             Cash operation type b            *
      *B/FV                           'B'                              *
      *B.MF SW-MODP                   Data modification in input panel *
      *B.FV   SW-MOD-PANLYE           Modifications                    *
      *B/FV                           'S'                              *
      *B.FV   SW-MOD-PANLNO           No modifications                 *
      *B/FV                           'N'                              *
      *B.FV   SW-MOD-PANLNOTH         No apply. Input different than   *
      *B/FV                           output                           *
      *B/FV                           ''                               *
      *B.IF PNT-INPCPY                Data map pointer on              *
      *B/IF                           input/output screen              *
      *B.IF SW-PA                     It informs on if there is paper  *
      *B.FV   SW-YES-PAPE             Yes paper                        *
      *B/FV                           'S'                              *
      *B.FV   SW-NO-PAPER             No paper                         *
      *B/FV                           'N'                              *
      *B.IF FCC-INPOPE                Curreny code of input operation  *
      *B.IF SW-TYP-INP                Input type                       *
      *B.FV   SW-INP-BMSM             Bms map type                     *
      *B/FV                           'B'                              *
      *B.FV   SW-INP-CPYTY            Copy type                        *
      *B/FV                           'C'                              *
      *B/FV                           'G'                              *
      *B.FV   SW-INP-LESS-2K-CPYTY    Copy type (negative 2k)          *
      *B/FV                           'C'                              *
      *B.FV   SW-INP-MORE2KCPYTY      Copy type (positive 2k)          *
      *B/FV                           'G'                              *
      *B.IF FILLER                    FILLER                           *
      *B.MF AUTHORIZATIO              Authorizations (input/output)    *
      *B.MF TB-AUTH                   Authorizations                   *
      *B.MF TB-RE-AUT                 Authorizations                   *
      *B.MF TB-AUT-ERR                Error code to authorize          *
      *B.MF TB-AUT-STATUS             Situation that is desired to     *
      *B/MF                           authorize                        *
      *B.MF SW-AUTOR                  Flag: error pending of           *
      *B/MF                           authorization                    *
      *B.FV   SW-AUT-PENDYES          Pending of authorization         *
      *B/FV                           'S'                              *
      *B.FV   SW-AUT-PENDINO          No pending of authorization      *
      *B/FV                           'N'                              *
      *B/FV                           ' '                              *
      *B.MF AMT-AUTHORIZ              Amount pending of authorization  *
      *B.MF AUTREFEREN                Operation reference depending    *
      *B/MF                           on the application               *
      *B.MF SW-ERR-AUT-ALN            Error in alnova authorization    *
      *B.FV   SW-ERR-AUT-YESALNOVA    Error in authorization           *
      *B/FV                           user/password validation         *
      *B/FV                           'S'                              *
      *B.MF FILLER                    FILLER                           *
      *B.OF AUXAUTHORIZATION          Authorizations (output pointer)  *
      *B.OF SEQNUM                    Authorization sequence number    *
      *B.OF 1-SEQNUM                  Authorization sequence number    *
      *B.OF AUTHPNT                   Pointer to authorizations data   *
      *B.OF 1-AUTHPNT                 Pointer to authorizations data   *
      *B.MF CONVERS                   Conversion data (input/output)   *
      *B.MF SW-STA                    Status                           *
      *B.FV   SW-BEGINNING-STA        Starting                         *
      *B/FV                           'I'                              *
      *B.FV   SW-CONTINUAT-STA        Continuation                     *
      *B/FV                           'C'                              *
      *B.FV   SW-CONFIRMAT-STA        Confirmation                     *
      *B/FV                           'X'                              *
      *B.MF CASE                      Application case                 *
      *B.MF ADATA                     Own application data             *
      *B.MF A1-DTA-AP                 Own application data             *
      *B.MF FILLER                    FILLER                           *
      *B.MF DYNAMREPORT               Used data by dinamic tables list *
      *B.MF DES-TBL                   Tabla name for dynamic list      *
      *B.MF POSITION-COM              Position within application      *
      *B/MF                           commarea for where sentence      *
      *B.MF LENGTH-COMMA              Length within application        *
      *B/MF                           commarea for where sentence      *
      *B.MF LNG-TBLDYCRP              Table language for dynamic list  *
      *B.MF DTA-LTH                   Length of additional own         *
      *B/MF                           application data                 *
      *B.MF DTA-PNT                   Pointer of additional own        *
      *B/MF                           application data                 *
      *B.MF SW-EXTNNTWK               External netname operation       *
      *B.FV   SW-EXT-NTWKYES          Yes external netname operation   *
      *B/FV                           'S'                              *
      *B.MF PNT-INT-MSG               Pointer to internal message      *
      *B.MF SW-PNT-INTMSG             Pointer to internal message      *
      *B.FV   SW-PNT-EMPTY-MSG        Pointer to empty message         *
      *B/FV                           HIGH-VALUES                      *
      *B.MF PNT-NOALN                 Pointer to alnova data           *
      *B.MF FILLER                    FILLER                           *
      *B.MF DTA-NEXTTRN               Next transaction data            *
      *B.MF SW-NEXTTRNS               Code of the transaction to wich  *
      *B/MF                           transfer the control             *
      *B.FV   SW-NEX-LASTNEXTTRNS     To the last wich gave us the     *
      *B/FV                           control                          *
      *B/FV                           'ULTI'                           *
      *B.FV   SW-NEX-SAMENEXTTRNS     To the same                      *
      *B/FV                           'SAME'                           *
      *B.FV   SW-NEX-MENUNEXTTRNS     To the main menu                 *
      *B/FV                           'MENU'                           *
      *B.FV   SW-NEX-EMPTYNEXTTRNS    To none                          *
      *B/FV                           SPACES                           *
      *B.MF SW-AUTOMAT                Flag of automatic roll-out in    *
      *B/MF                           next transaction                 *
      *B.FV   SW-AUT-ROLLOUTYE        Yes automatic roll-out           *
      *B/FV                           'S'                              *
      *B.FV   SW-AUT-ROLLOUTNO        No automatic roll-out            *
      *B/FV                           'N'                              *
      *B/FV                           ' '                              *
      *B.MF SW-ACT                    Action                           *
      *B.FV   SW-88-PROGRAMACTIO      Program                          *
      *B/FV                           'PRG'                            *
      *B.FV   SW-88-TERMINALACTI      Netname                          *
      *B/FV                           'TER'                            *
      *B/FV                           ' '                              *
      *B.IF SW-CHA                    Chain                            *
      *B.FV   SW-BEGINNING-CHA        Start chain                      *
      *B/FV                           'I'                              *
      *B.FV   SW-ADDITIONA-CHA        Add to chain                     *
      *B/FV                           'A'                              *
      *B.IF CHAICASE                  Status used when moving accross  *
      *B/IF                           the chain                        *
      *B.IF DATA-CHAI                 Own application data used when   *
      *B/IF                           moving accross the chain         *
      *B.OF OUT-TERMINA               Terminal output data             *
      *B.OF SW-ERRCOD                 Error code                       *
      *B.FV   SW-ERR-EMPTYERRCOD      No error code                    *
      *B/FV                           SPACES                           *
      *B.OF SW-COD-WA1                Warning code 1                   *
      *B.FV   SW-WAR-EMPTWARNCOD1     No warning code 1                *
      *B/FV                           SPACES                           *
      *B.OF SW-COD-WA2                Warning code 2                   *
      *B.FV   SW-WAR-EMPTWARNCOD2     No warning code 2                *
      *B/FV                           SPACES                           *
      *B.OF ERR-VARIA1                Variable 1 to include in error   *
      *B/OF                           message                          *
      *B.OF ERR-VARIA2                Variable 2 to include in error   *
      *B/OF                           message                          *
      *B.OF WARN1VARIA1               Variable 1 to include in         *
      *B/OF                           warning message 1                *
      *B.OF WARN1VARIA2               Variable 2 to include in         *
      *B/OF                           warning message 1                *
      *B.OF WARN2VARIA1               Variable 1 to include in         *
      *B/OF                           warning message 2                *
      *B.OF WARN2VARIA2               Variable 2 to include in         *
      *B/OF                           warning message 2                *
      *B.OF AMT-DISPENSE              Dispenser amount                 *
      *B.OF LOCAL-EJOURN              Field to update in local         *
      *B/OF                           electronic journal               *
      *B.OF SW-TYP-OUTP               Screen to send to the terminal   *
      *B.FV   SW-OUT-TYP-INPUTSC      The input one                    *
      *B/FV                           'E'                              *
      *B.FV   SW-OUT-TYP-OUTPUTS      The output one                   *
      *B/FV                           'S'                              *
      *B.FV   SW-OUT-TYP-ARCSCRL      Architecture scroll              *
      *B/FV                           'P'                              *
      *B.FV   SW-OUT-TYP-COPYSCRE     No bms fixed copy output         *
      *B/FV                           'C'                              *
      *B.FV   SW-OUT-TYP-NONESC       None                             *
      *B/FV                           ''                               *
      *B.OF OUT-COPY                  Name of the output copy          *
      *B.OF OUT-PANEL                 Name of the output BMS panel     *
      *B.OF TB-DESTI                  Terminal destination output      *
      *B/OF                           information                      *
      *B.OF TB-RE-DEST                Terminal destination output      *
      *B/OF                           information                      *
      *B.OF TB-DES1                   TS prefix contents the output    *
      *B.OF TB-SCRDOCU                Destination flag (screen /       *
      *B/OF                           document)                        *
      *B.OF TB-DOCNUM                 Document number                  *
      *B.OF TB-FSTLINDOC              Document first line position     *
      *B.OF TB-9-FSTLINDOC            Document first line position     *
      *B.OF TB-FORM                   Output form code                 *
      *B.OF TB-DISKP                  File disk to write on ps         *
      *B.OF TB-DES-DES-FIL            File name to write on ps         *
      *B.OF TB-DES-FILEUSE            File use to write on ps          *
      *B.OF TB-LNG                    Output language code             *
      *B.IF DTA-SCR                   Data for pagination handling     *
      *B.IF DTA-CONT                  Generic list content             *
      *B.IF TB-ALLWSELEC              Digits to admit as selection     *
      *B/IF                           field                            *
      *B.IF TB-RE-ALLWSELE            Digits to admit as selection     *
      *B/IF                           field                            *
      *B.IF TB-ALL-SEL                Digits to admit as selection     *
      *B/IF                           field                            *
      *B.IF SW-VRSSELE                Allowed multiselection flag      *
      *B.FV   SW-VRS-SELECTYES        Allowed selection                *
      *B/FV                           'S'                              *
      *B.FV   SW-VRS-SELECTINO        No allowed selection             *
      *B/FV                           'N'                              *
      *B.IF FIXEDMARGIN               Margin to maintain on left shift *
      *B.IF 9-FIXEDMARGIN             Margin to maintain on left shift *
      *B.IF T-PF                      Allowed function keys            *
      *B.IF T-RE-P                    Allowed function keys            *
      *B.IF T-NUM-PF                  Allowed key number               *
      *B.IF T-TXT-PF                  Key literal to display on panel  *
      *B.IF T-SEL-PF                  Selection function key           *
      *B.IF SW-ADVPAG                 Flag of control return to list   *
      *B/IF                           with pf8                         *
      *B.FV   SW-ADV-ADVPAGYE         Returned control                 *
      *B/FV                           'S'                              *
      *B.FV   SW-ADV-ADVPAGNO         No returned control              *
      *B/FV                           'N'                              *
      *B/FV                           ' '                              *
      *B.IF SW-FLG-DTAMO              Modification flag in data line   *
      *B.FV   SW-DTA-YESALLWMODI      Allowed modification             *
      *B/FV                           'S'                              *
      *B.FV   SW-DTA-NOALLWMODIF      No allowed modification          *
      *B/FV                           'N'                              *
      *B.IF SCREENLINE                Screen line used by ts           *
      *B/IF                           management program               *
      *B.IF SCREENCOLU                Screen column used by ts         *
      *B/IF                           management program               *
      *B.IF NUM-HEALINE               Number of fixed headings line    *
      *B.IF 9-NUM-HEALINE             Number of fixed headings line    *
      *B.IF SW-FLG-LTRSCRL            Lateral scroll flag              *
      *B.FV   SW-LTR-SCRLLTRYE        Performed lateral scroll         *
      *B/FV                           'S'                              *
      *B/FV                           ' '                              *
      *B.FV   SW-LTR-SCRLLTRNO        No performed lateral scroll      *
      *B/FV                           'N'                              *
      *B.IF NUM-SELECTITEM            Number of selected item          *
      *B.IF NUM-MAXLST                Maxim item number to list on gts *
      *B.IF SW-FLG-HEADVAR            Heading variable flag            *
      *B.FV   SW-HEA-YESHEADVAR       Yes heading variable             *
      *B/FV                           'S'                              *
      *B.FV   SW-HEA-NOHEADVARI       No heading variable              *
      *B/FV                           'N'                              *
      *B/FV                           ' '                              *
      *B.IF COPYGTSOUTP               Copy gts output                  *
      *B.IF SUFFIX-EDITION            Suffix edition                   *
      *B.IF SUFFIX-DATE               Date suffix                      *
      *B.IF SUFFIX-NUM                Number suffix                    *
      *B.IF FILLER                    FILLER                           *
      *B.OF DTA-ANALI                 Application output, data for     *
      *B/OF                           analytic and statistics          *
      *B.OF ENT-ANALITI               Analytic destination entity      *
      *B.OF 9-ENT-ANALITI             Analytic destination entity      *
      *B.OF CEN-ANALIT                Analytic destination center      *
      *B.OF 9-CEN-ANALIT              Analytic destination center      *
      *B.OF ANALITICPROD              Analytic product key             *
      *B.OF A1-ANALITICPRO            Analytic product key             *
      *B.OF ACC-ANALITI               Account number                   *
      *B.OF COD-ANLSERV               Service code                     *
      *B.OF FILLER                    FILLER                           *
      *B.OF 1-ANALITIC-GROU           Analytic group                   *
      *B.OF CUS-ANALITI               Customer                         *
      *B.OF AMT-ANALITI               Amount                           *
      *B.OF ANALITICSPR               Subproduct                       *
      *B.OF ANALITICPUR               Purpose                          *
      *B.OF ANALITICCOLT              Collateral                       *
      *B.OF SUBCLASSIF                Transaction sub-classification   *
      *B.OF A2-ANALITIC               Analytic group                   *
      *B.OF SW-OPT                    Type of performed operation      *
      *B.FV   SW-OPE-TYPEREG          Registration                     *
      *B/FV                           'A'                              *
      *B.FV   SW-OPE-TYPEANN          Annulment                        *
      *B/FV                           'B'                              *
      *B.FV   SW-OPE-TYPEMODI         Modification                     *
      *B/FV                           'M'                              *
      *B.FV   SW-OPE-TYPEINQUIRY      Inquiry                          *
      *B/FV                           'C'                              *
      *B.FV   SW-OPE-TYPEISSOPE       Issue                            *
      *B/FV                           'E'                              *
      *B.FV   SW-OPE-TYPEBTCHREQ      Batch request                    *
      *B/FV                           'P'                              *
      *B.FV   SW-OPE-TYPINPOUT        Input / output operation         *
      *B/FV                           'O'                              *
      *B.FV   SW-OPE-TYPNOTH          Nothing                          *
      *B/FV                           'N'                              *
      *B.FV   SW-OPE-TYPAUTFILTR      Automatic File Transfer          *
      *B/FV                           transaction                      *
      *B/FV                           '1'                              *
      *B.FV   SW-OPE-TYPESBISTRNS     Savings Bank Interchange System  *
      *B/FV                           transaction                      *
      *B/FV                           '2'                              *
      *B.FV   SW-OPE-TYPEACRUTRNS     Accrued transaction              *
      *B/FV                           '3'                              *
      *B.FV   SW-OPE-TYPEINQUTRNS     Inquiry transaction              *
      *B/FV                           '4'                              *
      *B.FV   SW-OPE-TYPEANNUTRNS     Annulment transaction            *
      *B/FV                           '5'                              *
      *B.FV   SW-OPE-TYPCANC          Cancellation                     *
      *B/FV                           '6'                              *
      *B.OF SW-ACCOU                  Accounting operation             *
      *B.FV   SW-ACC-OPERYES          Accounting operation             *
      *B/FV                           'S'                              *
      *B.FV   SW-ACC-OPERANO          No accounting operation          *
      *B/FV                           'N'                              *
      *B.OF DTA-APPLICA               Data of free use for the         *
      *B/OF                           application                      *
      *B.IF 2-ANL-GROUP               Analytic                         *
      *B.IF A1-2-ANALI-GROUP          Alnova area                      *
      *B.IF CHANN                     Channel                          *
      *B.MF SW-STTCOD                 Start code                       *
      *B.FV   SW-STT-NOSYNCP          No syncpoint                     *
      *B/FV                           'D '                             *
      *B.FV   SW-STT-YESSYNC          Yes syncpoint                    *
      *B/FV                           'DS'                             *
      *B.FV   SW-DPL                  Started by dpl                   *
      *B/FV                           'D '                             *
      *B/FV                           'DS'                             *
      *B.FV   SW-STT-TDQ              TD queue                         *
      *B/FV                           'QD'                             *
      *B.FV   SW-STT-WTHTDATASTT      Without data                     *
      *B/FV                           'S '                             *
      *B.FV   SW-STT-WITHDATASTT      With data                        *
      *B/FV                           'SD'                             *
      *B.FV   SW-FEPI                 Qcrmfepi                         *
      *B/FV                           'SZ'                             *
      *B.FV   SW-STT-TERM             Terminal                         *
      *B/FV                           'TD'                             *
      *B.FV   SW-STT-ALLOWEDSYNCPOIN  Allowed syncpoint                *
      *B/FV                           'DS'                             *
      *B/FV                           'QD'                             *
      *B/FV                           'S '                             *
      *B/FV                           'SD'                             *
      *B/FV                           'SZ'                             *
      *B/FV                           'TD'                             *
      *B.FV   SW-STT-NOALLOWEDSYNCPO No allowed syncpoint             *
      *B/FV                           'D '                             *
      *B.IF LOGON-USERID              Logon user                       *
      *B.IF SW-PREFORMAT              Preformat                        *
      *B.FV   SW-PRE-YEPREFORMAT      Preformat yes                    *
      *B/FV                           'Y'                              *
      *B.FV   SW-PRE-NOPREFORMAT      Preformat no                     *
      *B/FV                           'N'                              *
      *B.OF SW-FLG-MGCAL              Alarm flag                       *
      *B.FV   SW-MGC-NOMAGICALAR      No alarm                         *
      *B/FV                           '0'                              *
      *B.FV   SW-MGC-SALEMAGICALARM   Sale                             *
      *B/FV                           '1'                              *
      *B.FV   SW-MGC-THREATMAGICALARM Threat                           *
      *B/FV                           '2'                              *
      *B.FV   SW-MGC-GRACEPRDMAGICAL Grace period                     *
      *B/FV                           '3'                              *
      *B.OF SW-FLG-ANLPSBCH           Analytic flag                    *
      *B.FV   SW-ANL-PSB              Passbook                         *
      *B/FV                           'LIB'                            *
      *B.FV   SW-ANL-CHK              Check                            *
      *B/FV                           'CHE'                            *
      *B.OF EXCEPTION-TYPE1           Exception type                   *
      *B.OF FLG-ANALCHBK              Analytic check book flag         *
      *B.OF NUM-ANALCHBK              Analytic check book number       *
      *B.OF SW-TYP-ANLCENTE           Analytic center type             *
      *B.FV   SW-ANL-BRNCENT-TYP      Branch                           *
      *B/FV                           'O'                              *
      *B.FV   SW-ANL-ZONECEN-TYP      Zone                             *
      *B/FV                           'Z'                              *
      *B.FV   SW-ANL-RISKCENTER-TYP   Risk                             *
      *B/FV                           'I'                              *
      *B.FV   SW-ANL-REGCENT-TYP      Registration                     *
      *B/FV                           'R'                              *
      *B.OF SW-ANL-RISKAPRX           Analytic risk approximation      *
      *B.FV   SW-RIS-YESAPRX          Approximation                    *
      *B/FV                           'S'                              *
      *B.FV   SW-RIS-PROPSUBMIT       Proposal submitting              *
      *B/FV                           'E'                              *
      *B.OF ERR-INFORMATI             Error information                *
      *B.OF OBJECT-ERROR              Name of the object where the     *
      *B/OF                           error occurred                   *
      *B.OF SQLCODE                   DB2 return code                  *
      *B.OF SQLERRM                   DB2 error information            *
      *B.OF EIBFN                     CICS last function               *
      *B.OF EIBRSRCE                  CICS last resource               *
      *B.OF EIBRCODE                  CICS reply code                  *
      *B.OF EIBRESP1                  Condition caused by CICS last    *
      *B/OF                           function                         *
      *B.OF EIBRESP2                  Additional information to        *
      *B/OF                           EIBRESP1                         *
      *B.OF FILLER                    FILLER                           *
      ******************************************************************
      ******************************************************************
      *@MI             : MODIFICACIONES MULTI-IDIOMA                   *
      *C.E.C.M.C.      : MODIFICACIONES MEDIOS DE PAGO                 *
      *@MAUT           : MODIFICACION PARA TRATAMIENTO AUTORIZACIONES  *
      *@AL0213D (DIC94): ANADIR TERMINALES 4B (NIVELES 88)             *
      *@AL0214D (ENE95): INCLUSION DE UN PUNTERO PARA CONEXION CON     *
      *                  OTROS SISTEMAS NO ALTAMIRA                    *
      *@AL0218D (ABR95): ANADIR TERMINAL PS/2 FFS - FOUNDATION         *
      *@CEC-210        : CREAR REDEFINICION DEL CAMPO CAA-TB-FORM PARA *
      *                  ENVIAR EL NOMBRE DE FICHERO AL PS PARA GRABAR *
      *                  INFORMACION CUANDO CAA-PANDOC = 'D'           *
      *@CEC-227        : NUEVO TIPO DE TERMINAL TAVE (C.AUTOR)         *
      *@AL0253D (JUN97): ADAPTACION PARA EURO                          *
      *@AI0002D 01NOV97: GESTION DE SCROLL MULTI-IDIOMA                *
      *@AI0003D 01NOV97: MEJORA DE LISTADOS DINAMICOS MULTI-IDIOMA     *
      *@AL0254D (ENE98): INCLUSION DE MODELO DE TERMINAL PARA PS-5     *
      *@AL0258D (MAY98): INCLUSION DE MODELO DE TERMINAL UNIVERSIDAD   *
      *@AL0259D (JUN98): ANADIR TERMINAL PARA ATENEA (CREDIT LYONNAIS) *
      *@AL0264D (NOV98): CUSTOMIZATION LINK24 (CENTROAUT)              *
      *@CEC-271 (NOV98): NUEVO NIVEL 88 EN CAA-SW-TRMMODEL PARA        *
      *                  ACTUALIZADORES DE LIBRETA CON VALOR 'AC'      *
      *@AL0266D (JUL99): CUSTOMIZATION POLCARD (CENTROAUT)             *
      *@CEC-291 (NOV99): NUEVO NIVEL 88 EN CAA-SW-TRMMODEL PARA        *
      *                  TELEFONO                                      *
      *@AL0270D (FEB00): ANADIR TERMINAL PS/8 WEB CLIENT               *
      *@AL0272D (FEB00): INVOCACION VIA DPL                            *
      *@AL0275D (FEB00): PROPAGACION DE CANAL                          *
      *@AL0274D (FEB00): ANADIR TERMINAL PS/9 X-PLATFORM               *
      *ALINFQG102 (MAR01) : SOPORTE A COPY FIJA NO BMS . NUEVO TIPOSAL *
      *ALINFQG103 (JUN01) : EDICION DE IMPORTES Y PORCENTAJES. VALOR   *
      *                     DE EDICION PARA LA INSTALACION.            *
      *ALINFQG106 (JUN01) : EDICION DE FECHAS.VALOR DE EDICION PARA LA *
      *                     INSTALACION.                               *
      *ALINFQG108 (JUN01) : CONTROL SALIDAS ON-LINE GTS.FORMATO SALIDA *
      *                     ASOCIADO AL REGISTRO GTS.                  *
      *.B.MD.ALINFQA112 AJUSTES VARIOS ALNOVA 21022002                 *
      *.B.MD.ALINFQA114 TRANSACTIONAL COORDINATION ALNOVA 02042002     *
      *.B.MD. ALINFQA125-46 ALNOVA 2002-05-29 ADD REDEFINED FIELDS     *
      *.B.MD. JOG      2020-06-05  SE EGREGA TIPO DE CADEDA 51 EGLOBAL *
      ******************************************************************

       02 QGECCAA.
        03 QGECCAA-03.
      *OL.S
      *          **---------------------------------------**
      *          **------  ENTRADA A LA APLICACION  ------**
      *          **----------- DATOS GENERALES -----------**
      *          **---------------------------------------**
      *OL.E
          05 CAA-DTA-GENERAL.
             10 CAA-ENT-ACC                PIC X(04).
             10 CAA-9-ENT-ACC               REDEFINES CAA-ENT-ACC
                                           PIC 9(04).
             10 CAA-CEN-ACCOUNT            PIC X(04).
             10 CAA-9-CEN-ACCOUNT           REDEFINES CAA-CEN-ACCOUNT
                                           PIC 9(04).
             10 CAA-ACCO-NETNAME           PIC X(08).
             10 CAA-ACCO-TERMINAL          PIC X(04).
             10 CAA-DAT-ACCOUN             PIC X(08).
             10 CAA-9-DAT-ACCOUN            REDEFINES CAA-DAT-ACCOUN
                                           PIC 9(08).
             10 CAA-2DAT-ACCOUN            PIC X(10).
             10 CAA-DAT-ED-ACCOU           PIC X(10).
             10 CAA-DAT-OPERAT             PIC X(08).
             10 CAA-9-DAT-OPERAT            REDEFINES CAA-DAT-OPERAT
                                           PIC 9(08).
             10 CAA-2DAT-OPERAT            PIC X(10).
             10 CAA-DAT-ED-OPERA           PIC X(10).
             10 CAA-DAT-TRANSMI            PIC X(08).
             10 CAA-9-DAT-TRANSMI           REDEFINES CAA-DAT-TRANSMI
                                           PIC 9(08).
             10 CAA-2DAT-TRANSMI           PIC X(10).
             10 CAA-DAT-ED-TRANSM          PIC X(10).
             10 CAA-TIM-TRANSM             PIC X(06).
             10 CAA-9-TIM-TRANSM            REDEFINES CAA-TIM-TRANSM
                                           PIC 9(06).
             10 CAA-TIM-ED-TRANS           PIC X(08).
             10 CAA-NETNAME                PIC X(08).
             10 CAA-TERMINAL               PIC X(04).
             10 CAA-USERID                 PIC X(08).
             10 CAA-SW-SES                 PIC X(01).
                88 CAA-SW-MORNINGSESION                VALUE 'M'.
                88 CAA-SW-AFTERNSESION                 VALUE 'T'.
             10 CAA-SW-TYPTRM              PIC X(02).
                88 CAA-SW-TRM-4700-TERMI               VALUE '11'.
                88 CAA-SW-TRM-5935-TERMI               VALUE '12'.
                88 CAA-SW-TRM-3270-TERMI               VALUE
             '20', '28', '29'.
                88 CAA-SW-TRM-PS1-TERMIN               VALUE '13'.
                88 CAA-SW-TRM-PS2-TERMIN               VALUE '14'.
                88 CAA-SW-TRM-PS3-TERMIN               VALUE '15'.
                88 CAA-SW-TRM-PS4-TERMIN               VALUE '17'.
                88 CAA-SW-TRM-PS5-TERMIN               VALUE '18'.
                88 CAA-SW-TRM-PS6-TERMIN               VALUE '19' '21'.
                88 CAA-SW-TRM-ATENEA-TERMI             VALUE '21'.
      *@PAL0270D-0200
                88 CAA-SW-TRM-PS8-TERMIN               VALUE '25'.
      *@PAL0274D-0200
                88 CAA-SW-TRM-PS9-TERMIN               VALUE '26'.
      *@FAL0274D-0200
      *         88 CAA-SW-TRM-PS-TERMI  VALUE '13' '14' '15' '16'
      *                                       '17' '18' '19' '21'.
      *@PAL0274D-0200
      *         88 CAA-SW-TRM-PS-TERMI  VALUE '13' '14' '15' '16'
      *                                       '17' '18' '19' '21' '25'.
                88 CAA-SW-TRM-PS-TERMI                 VALUE '13' '14' '
      -             '15' '16' '17'
             '18' '19' '21' '25' '26'.
      *@FAL0274D-0200
      *@FAL0270D-0200
                88 CAA-SW-TRM-VIDEOTEX-TERMI           VALUE '16'.
                88 CAA-SW-TRM-INPUNIV-TERM             VALUE '35'.
                88 CAA-SW-TRM-OUTUNIV-TERM             VALUE '36'.
                88 CAA-SW-TRM-UNIV-TERMI               VALUE '35' '36'.
                88 CAA-SW-TRM-ATM1-TERMINA             VALUE '40'.
                88 CAA-SW-1-TRM-NASB-TERM              VALUE '41'.
                88 CAA-SW-2-TRM-NASB-TERM              VALUE '42'.
                88 CAA-SW-TRM-NASB-TERMI               VALUE '41' '42'.
                88 CAA-SW-TRM-POS-TERMI                VALUE '43'.
                88 CAA-SW-TRM-INPKRN-TERM              VALUE '44'.
                88 CAA-SW-TRM-OUTKRN-TERM              VALUE '45'.
                88 CAA-SW-TRM-PARMKRN-TER              VALUE '52'.
                88 CAA-SW-TRM-KORONA-TERMI             VALUE
             '44' '45' '52'.
                88 CAA-SW-TRM-ISSSSPM-TERMI            VALUE '46'.
                88 CAA-SW-TRM-ACQSSPM-TERMI            VALUE '47'.
                88 CAA-SW-TRM-RECVSSPM-TERM            VALUE '48'.
                88 CAA-SW-TRM-UPDSSPM-TERMI            VALUE '49'.
                88 CAA-SW-TRM-FICSSPM-TERM             VALUE '50' '51'.
                88 CAA-SW-TRM-SSPM-TERMI
                                   VALUE '46' '47' '48' '49' '50' '51'.
                88 CAA-SW-TRM-INPUT-TERMINA            VALUE '53'.
                88 CAA-SW-TRM-REAL4B-TERMIN            VALUE '54'.
                88 CAA-SW-TRM-FIC4B-TERMIN             VALUE '55'.
                88 CAA-SW-TRM-4B-TERMI                 VALUE '54' '55'.
                88 CAA-SW-TRM-ATMLINK24-TERM           VALUE '56'.
                88 CAA-SW-TRM-POSLINK24-TERM           VALUE '57'.
                88 CAA-SW-TRM-EXTNNETLINK24T           VALUE '58'.
                88 CAA-SW-TRM-OUTINK24-TERMI           VALUE '59'.
                88 CAA-SW-TRM-LINK24-TERMI             VALUE
             '56' '57' '58' '59'.
                88 CAA-SW-TRM-TAVETERMINALTY           VALUE '60'.
                88 CAA-SW-TRM-INPPOLCARD-TERM          VALUE '61'.
                88 CAA-SW-TRM-VIRPOLCARD-TERM          VALUE '62'.
                88 CAA-SW-TRM-OUTPOLCARD-TERM          VALUE '63'.
                88 CAA-SW-TRM-POLCARD-TERMI            VALUE
             '61' '62' '63'.

                88 CAA-SW-TRM-AUTCEN-TERMINAL
                                   VALUE '40' '41' '42' '43' '44'
             '45' '46' '47' '48' '49'
             '50' '51' '52' '53' '54' '55'
             '35' '36'
             '60'
             '56' '57' '58' '59'
             '61' '62' '63'.
             10 CAA-CICS                   PIC X(04).
             10 CAA-COD-TRA                PIC X(04).
             10 CAA-SW-TYP-PROCE           PIC X(01).
                88 CAA-SW-PRO-ONLINE-PROCES            VALUE 'O'.
                88 CAA-SW-PRO-AUTHORIZ-PROC            VALUE 'A'.
                88 CAA-SW-PRO-TELEDISK-PROC            VALUE 'T'.
                88 CAA-SW-PRO-OFFLINE-PROC             VALUE 'F'.
             10 CAA-SW-APPSTATUS           PIC X(01).
                88 CAA-SW-APP-AC                       VALUE 'A'.
                88 CAA-SW-APP-INACT                    VALUE 'D'.
                88 CAA-SW-APP-SESCHANGE                VALUE 'C'.
                88 CAA-SW-APP-RETRIEVA                 VALUE 'R'.
             10 CAA-NUM-RETRYDB2LO         PIC S9(4) COMP.
             10 CAA-NUM-SEQUE              PIC X(05).
             10 CAA-9-NUM-SEQUE  REDEFINES CAA-NUM-SEQUE
                                           PIC 9(05).
             10 CAA-GATAPB-VERS            PIC X(04).
             10 CAA-SW-LNG-TERM            PIC X(01).
                88 CAA-SW-TER-LNGNOTHI                 VALUE ' '.
                88 CAA-SW-TER-LANGUA1                  VALUE 'E'.
                88 CAA-SW-TER-LANGUA2                  VALUE 'C'.
                88 CAA-SW-TER-LANGUA3                  VALUE 'G'.
                88 CAA-SW-TER-LANGUA4                  VALUE 'I'.
                88 CAA-SW-TER-LANGUA5                  VALUE 'F'.
                88 CAA-SW-TER-LANGUA6                  VALUE 'P'.
             10 CAA-SW-A1-APPSTA           PIC X(01).
                88 CAA-SW-APP-SNGF                     VALUE 'N'.
                88 CAA-SW-APP-CONV                     VALUE 'C'.
                88 CAA-SW-APP-SNGR                     VALUE 'E'.
                88 CAA-SW-APP-DOUB                     VALUE 'B'.
                88 CAA-SW-APP-WTHT                     VALUE 'S'.
                88 CAA-SW-APP-CPLT                     VALUE 'M'.
                88 CAA-SW-APP-NENT                     VALUE 'X'.
             10 CAA-SW-TRMMODEL            PIC X(02).
                88 CAA-SW-TRM-INTERNETMOD              VALUE 'IN'.
                88 CAA-SW-TRM-MUSEUMMOD                VALUE 'MU'.
                88 CAA-SW-TRM-UPDATEMODEL              VALUE 'AC'.
                88 CAA-SW-TRM-TELEPHONMOD              VALUE 'TE'.
      *ALINFQG108-INI
      *      10 FILLER                      PIC X(15).
             10 CAA-APPLICATION            PIC X(02).
      *.MC.S ALINFQA114
      *      10 FILLER                      PIC X(13).
             10 CAA-COD-MULTTRNS           PIC X(4).
             10 FILLER                     PIC X(09).
      *.MC.E ALINFQA114
      *ALINFQG108-FIN
      *OL.S
      *          **---------------------------------------**
      *          **------  ENTRADA A LA APLICACION  ------**
      *          **---------- DATOS DEL MENSAJE ----------**
      *          **---------------------------------------**
      *OL.E
          05 CAA-DTA-INPUTTRM.
             10 CAA-PRKEY                  PIC X(02).
             10 CAA-SW-CSH                 PIC X(01).
                88 CAA-SW-A-USECSH                     VALUE 'A'.
                88 CAA-SW-B-USECSH                     VALUE 'B'.
             10 CAA-SW-MODP                PIC X(01).
                88 CAA-SW-MOD-PANLYE                   VALUE 'S'.
                88 CAA-SW-MOD-PANLNO                   VALUE 'N'.
                88 CAA-SW-MOD-PANLNOTH                 VALUE ' '.
             10 CAA-PNT-INPCPY              POINTER.
             10 CAA-SW-PA                  PIC X(1).
                88 CAA-SW-YES-PAPE                     VALUE 'S'.
                88 CAA-SW-NO-PAPER                     VALUE 'N'.
             10 CAA-FCC-INPOPE             PIC X(03).
      *.MC.S ALINFQA125-46
      *      10 FILLER                      PIC X(06).
             10 CAA-SW-TYP-INP             PIC X(01).
                       88 CAA-SW-INP-BMSM              VALUE 'B'.
                       88 CAA-SW-INP-CPYTY             VALUE 'C' 'G'.
                       88 CAA-SW-INP-LESS-2K-CPYTY     VALUE 'C'.
                       88 CAA-SW-INP-MORE2KCPYTY       VALUE 'G'.
             10 FILLER                     PIC X(05).
      *.MC.E ALINFQA125-46
      *OL.S
      *          **---------------------------------------**
      *          **---  AUTORIZACIONES (ENTRADA/SALIDA) --**
      *          **---------------------------------------**
      *OL.E
          05 CAA-AUTHORIZATIO.
             10 CAA-TB-AUTH                PIC X(0150).
             10 CAA-TB-RE-AUT               REDEFINES CAA-TB-AUTH
                                            OCCURS 10 TIMES.
                15 CAA-TB-AUT-ERR          PIC X(07).
                15 CAA-TB-AUT-STATUS       PIC X(08).
             10 CAA-SW-AUTOR               PIC X(01).
                88 CAA-SW-AUT-PENDYES                  VALUE 'S'.
                88 CAA-SW-AUT-PENDINO                  VALUE 'N' ' '.
             10 CAA-AMT-AUTHORIZ           PIC S9(13)      COMP-3.
             10 CAA-AUTREFEREN             PIC X(20).
             10 CAA-SW-ERR-AUT-ALN         PIC X(1).
                88 CAA-SW-ERR-AUT-YESALNOVA            VALUE 'S'.
             10 FILLER                     PIC X(21).
      *OL.S
      *          **---------------------------------------**
      *          **---  AUTORIZACIONES (PTRO AUXILIAR)  --**
      *          **---------------------------------------**
      *OL.E
          05 CAA-AUXAUTHORIZATION.
             10 CAA-SEQNUM                 PIC S9(07) COMP-3.
             10 CAA-1-SEQNUM                REDEFINES  CAA-SEQNUM
                                           PIC X(04).
             10 CAA-AUTHPNT                 POINTER.
             10 CAA-1-AUTHPNT               REDEFINES CAA-AUTHPNT
                                           PIC X(04).
      *OL.S
      *          **---------------------------------------**
      *          **-  DATOS CONVERSACION ENTRADA/SALIDA  -**
      *          **---------------------------------------**
      *OL.E
          05 CAA-CONVERS.
             10 CAA-SW-STA                 PIC X(01).
                88 CAA-SW-BEGINNING-STA                VALUE 'I'.
                88 CAA-SW-CONTINUAT-STA                VALUE 'C'.
                88 CAA-SW-CONFIRMAT-STA                VALUE 'X'.
             10 CAA-CASE                   PIC X(01).
             10 CAA-ADATA                  PIC X(30).
             10 CAA-A1-DTA-AP     REDEFINES CAA-ADATA.
                15 FILLER                  PIC X(11).
                15 CAA-DYNAMREPORT.
                   20 CAA-DES-TBL          PIC X(10).
                   20 CAA-POSITION-COM     PIC 9(4).
                   20 CAA-LENGTH-COMMA     PIC 9(4).
                   20 CAA-LNG-TBLDYCRP     PIC X(1).
             10 CAA-DTA-LTH                PIC S9(05)      COMP-3.
             10 CAA-DTA-PNT                 POINTER.
             10 CAA-SW-EXTNNTWK            PIC X(1).
                88 CAA-SW-EXT-NTWKYES                  VALUE 'S'.
             10 CAA-PNT-INT-MSG             POINTER.
             10 CAA-SW-PNT-INTMSG
                        REDEFINES  CAA-PNT-INT-MSG
                                           PIC X(4).
                88 CAA-SW-PNT-EMPTY-MSG                VALUE
                    HIGH-VALUES.
             10 CAA-PNT-NOALN               POINTER.
             10 FILLER                     PIC X(01).
      *OL.S
      *          **---------------------------------------**
      *          **--  DATOS DE SIGUIENTE TRANSACCION   --**
      *          **---------------------------------------**
      *OL.E
          05 CAA-DTA-NEXTTRN.
             10 CAA-SW-NEXTTRNS            PIC X(04).
                88 CAA-SW-NEX-LASTNEXTTRNS             VALUE 'ULTI'.
                88 CAA-SW-NEX-SAMENEXTTRNS             VALUE 'SAME'.
                88 CAA-SW-NEX-MENUNEXTTRNS             VALUE 'MENU'.
                88 CAA-SW-NEX-EMPTYNEXTTRNS            VALUE SPACES.
             10 CAA-SW-AUTOMAT             PIC X(01).
                88 CAA-SW-AUT-ROLLOUTYE                VALUE 'S'.
                88 CAA-SW-AUT-ROLLOUTNO                VALUE 'N' ' '.
             10 CAA-SW-ACT                 PIC X(03).
                88 CAA-SW-88-PROGRAMACTIO              VALUE 'PRG'.
                88 CAA-SW-88-TERMINALACTI              VALUE
             'TER', '   '.
             10 CAA-SW-CHA                 PIC X(01).
                88 CAA-SW-BEGINNING-CHA                VALUE 'I'.
                88 CAA-SW-ADDITIONA-CHA                VALUE 'A'.
             10 CAA-CHAICASE               PIC X(01).
             10 CAA-DATA-CHAI              PIC X(30).
      *OL.S
      *          **---------------------------------------**
      *          **------  SALIDA DE LA APLICACION  ------**
      *          **------     DATOS DEL MENSAJE     ------**
      *          **---------------------------------------**
      *OL.E
          05 CAA-OUT-TERMINA.
             10 CAA-SW-ERRCOD              PIC X(07).
                88 CAA-SW-ERR-EMPTYERRCOD              VALUE SPACES.
             10 CAA-SW-COD-WA1             PIC X(07).
                88 CAA-SW-WAR-EMPTWARNCOD1             VALUE SPACES.
             10 CAA-SW-COD-WA2             PIC X(07).
                88 CAA-SW-WAR-EMPTWARNCOD2             VALUE SPACES.
             10 CAA-ERR-VARIA1             PIC X(20).
             10 CAA-ERR-VARIA2             PIC X(20).
             10 CAA-WARN1VARIA1            PIC X(20).
             10 CAA-WARN1VARIA2            PIC X(20).
             10 CAA-WARN2VARIA1            PIC X(20).
             10 CAA-WARN2VARIA2            PIC X(20).
             10 CAA-AMT-DISPENSE           PIC S9(13)      COMP-3.
             10 CAA-LOCAL-EJOURN           PIC X(80).
             10 CAA-SW-TYP-OUTP            PIC X(01).
                88 CAA-SW-OUT-TYP-INPUTSC              VALUE 'E'.
                88 CAA-SW-OUT-TYP-OUTPUTS              VALUE 'S'.
                88 CAA-SW-OUT-TYP-ARCSCRL              VALUE 'P'.
      *ALINFQG102-INI
                88 CAA-SW-OUT-TYP-COPYSCRE             VALUE 'C'.
      *ALINFQG102-FIN
                88 CAA-SW-OUT-TYP-NONESC               VALUE ' '.
             10 CAA-OUT-COPY               PIC X(08).
             10 CAA-OUT-PANEL              PIC X(08).
             10 CAA-TB-DESTI               PIC X(0075).
             10 CAA-TB-RE-DEST              REDEFINES CAA-TB-DESTI
                                            OCCURS 5  TIMES.
                15 CAA-TB-DES1             PIC X(04).
                15 CAA-TB-SCRDOCU          PIC X(01).
                15 CAA-TB-DOCNUM           PIC X(01).
                15 CAA-TB-FSTLINDOC        PIC X(02).
                15 CAA-TB-9-FSTLINDOC       REDEFINES CAA-TB-FSTLINDOC
                                           PIC 9(02).
                15 CAA-TB-FORM             PIC X(06).
                15 CAA-TB-DISKP REDEFINES CAA-TB-FORM.
                   20 CAA-TB-DES-DES-FIL   PIC X(5).
                   20 CAA-TB-DES-FILEUSE   PIC X.
                15 CAA-TB-LNG              PIC X(01).
      *OL.S
      *          **---------------------------------------**
      *          **------  SALIDA DE LA APLICACION  ------**
      *          **-- DATOS PARA GESTION DE PAGINACION  --**
      *          **---------------------------------------**
      *OL.E
          05 CAA-DTA-SCR.
             10 CAA-DTA-CONT               PIC X(50).
             10 CAA-TB-ALLWSELEC           PIC X(0010).
             10 CAA-TB-RE-ALLWSELE          REDEFINES CAA-TB-ALLWSELEC
                                            OCCURS 10 TIMES.
                15 CAA-TB-ALL-SEL          PIC X(01).
             10 CAA-SW-VRSSELE             PIC X(01).
                88 CAA-SW-VRS-SELECTYES                VALUE 'S'.
                88 CAA-SW-VRS-SELECTINO                VALUE 'N'.
             10 CAA-FIXEDMARGIN            PIC X(02).
             10 CAA-9-FIXEDMARGIN           REDEFINES CAA-FIXEDMARGIN
                                           PIC 9(02).
             10 CAA-T-PF                   PIC X(0072).
             10 CAA-T-RE-P                  REDEFINES CAA-T-PF
                                            OCCURS 8  TIMES.
                15 CAA-T-NUM-PF            PIC X(02).
                15 CAA-T-TXT-PF            PIC X(06).
                15 CAA-T-SEL-PF            PIC X(01).
             10 CAA-SW-ADVPAG              PIC X(01).
                88 CAA-SW-ADV-ADVPAGYE                 VALUE 'S'.
                88 CAA-SW-ADV-ADVPAGNO                 VALUE 'N' ' '.
             10 CAA-SW-FLG-DTAMO           PIC X(01).
                88 CAA-SW-DTA-YESALLWMODI              VALUE 'S'.
                88 CAA-SW-DTA-NOALLWMODIF              VALUE 'N'.
             10 CAA-SCREENLINE             PIC S9(05)      COMP-3.
             10 CAA-SCREENCOLU             PIC S9(05)      COMP-3.
             10 CAA-NUM-HEALINE            PIC X(02).
             10 CAA-9-NUM-HEALINE  REDEFINES CAA-NUM-HEALINE
                                           PIC 9(02).
             10 CAA-SW-FLG-LTRSCRL         PIC X(01).
                88 CAA-SW-LTR-SCRLLTRYE                VALUE 'S' ' '.
                88 CAA-SW-LTR-SCRLLTRNO                VALUE 'N'.
             10 CAA-NUM-SELECTITEM         PIC S9(05)    COMP-3.
             10 CAA-NUM-MAXLST             PIC S9(04)    COMP.
      *@PAL0284D-1100
      *      10 FILLER                      PIC X(15).
             10 CAA-SW-FLG-HEADVAR         PIC X(01).
                88 CAA-SW-HEA-YESHEADVAR               VALUE 'S'.
                88 CAA-SW-HEA-NOHEADVARI               VALUE 'N' ' '.
      *ALINFQG108-INI
      *      10 FILLER                      PIC X(14).
             10 CAA-COPYGTSOUTP            PIC X(8).
      *ALINFQG106-INI
          05 CAA-SUFFIX-EDITION.
             10 CAA-SUFFIX-DATE            PIC X(1).
      *ALINFQG106-FIN
      *ALINFQG103-INI
             10 CAA-SUFFIX-NUM             PIC X(1).
      *ALINFQG103-FIN
             10 FILLER                     PIC X(4).
      *ALINFQG108-FIN
      *@FAL0284D-1100
      *OL.S
      *          **---------------------------------------**
      *          **------  SALIDA DE LA APLICACION  ------**
      *          **------       DATOS PARA          ------**
      *          **------  ANALITICA Y ESTADISTICAS ------**
      *          **---------------------------------------**
      *OL.E
          05 CAA-DTA-ANALI.
             10 CAA-ENT-ANALITI            PIC X(04).
             10 CAA-9-ENT-ANALITI           REDEFINES CAA-ENT-ANALITI
                                           PIC 9(04).
             10 CAA-CEN-ANALIT             PIC X(04).
             10 CAA-9-CEN-ANALIT            REDEFINES CAA-CEN-ANALIT
                                           PIC 9(04).
             10 CAA-ANALITICPROD           PIC X(20).
      *.MC.S ALINFQA112
             10 CAA-A1-ANALITICPRO REDEFINES CAA-ANALITICPROD.
                15 CAA-ACC-ANALITI         PIC X(16).
                15 CAA-COD-ANLSERV         PIC X(02).
                15 FILLER                  PIC X(02).
      *.MC.E ALINFQA112
             10 CAA-1-ANALITIC-GROU.
                15 CAA-CUS-ANALITI         PIC X(08).
                15 CAA-AMT-ANALITI         PIC S9(13)V9(2) COMP-3.
                15 CAA-ANALITICSPR         PIC X(04).
                15 CAA-ANALITICPUR         PIC X(03).
                15 CAA-ANALITICCOLT        PIC X(01).
                15 CAA-SUBCLASSIF          PIC X(03).
             10 CAA-A2-ANALITIC  REDEFINES CAA-1-ANALITIC-GROU
                                           PIC X(27).
             10 CAA-SW-OPT                 PIC X(01).
                88 CAA-SW-OPE-TYPEREG                  VALUE 'A'.
                88 CAA-SW-OPE-TYPEANN                  VALUE 'B'.
                88 CAA-SW-OPE-TYPEMODI                 VALUE 'M'.
                88 CAA-SW-OPE-TYPEINQUIRY              VALUE 'C'.
                88 CAA-SW-OPE-TYPEISSOPE               VALUE 'E'.
                88 CAA-SW-OPE-TYPEBTCHREQ              VALUE 'P'.
                88 CAA-SW-OPE-TYPINPOUT                VALUE 'O'.
                88 CAA-SW-OPE-TYPNOTH                  VALUE 'N'.
      *.MC.S ALINFQA112
                88 CAA-SW-OPE-TYPAUTFILTR              VALUE '1'.
                88 CAA-SW-OPE-TYPESBISTRNS             VALUE '2'.
                88 CAA-SW-OPE-TYPEACRUTRNS             VALUE '3'.
                88 CAA-SW-OPE-TYPEINQUTRNS             VALUE '4'.
                88 CAA-SW-OPE-TYPEANNUTRNS             VALUE '5'.
                88 CAA-SW-OPE-TYPCANC                  VALUE '6'.
      *.MC.E ALINFQA112
             10 CAA-SW-ACCOU               PIC X(01).
                88 CAA-SW-ACC-OPERYES                  VALUE 'S'.
                88 CAA-SW-ACC-OPERANO                  VALUE 'N'.
             10 CAA-DTA-APPLICA            PIC X(20).
             10 CAA-2-ANL-GROUP            PIC X(30).
      *@PAL0272D-AL0275D-0200
             10 CAA-A1-2-ANALI-GROUP        REDEFINES CAA-2-ANL-GROUP.
                15 CAA-CHANN               PIC X(02).
                15 CAA-SW-STTCOD           PIC X(02).
                   88 CAA-SW-STT-NOSYNCP               VALUE 'D '.
                   88 CAA-SW-STT-YESSYNC               VALUE 'DS'.
                   88 CAA-SW-DPL                       VALUE 'D ' 'DS'.
                   88 CAA-SW-STT-TDQ                   VALUE 'QD'.
                   88 CAA-SW-STT-WTHTDATASTT           VALUE 'S '.
                   88 CAA-SW-STT-WITHDATASTT           VALUE 'SD'.
                   88 CAA-SW-FEPI                      VALUE 'SZ'.
                   88 CAA-SW-STT-TERM                  VALUE 'TD'.
                   88 CAA-SW-STT-ALLOWEDSYNCPOIN       VALUE
             'DS' 'QD' 'S ' 'SD' 'SZ' 'TD'.
                   88 CAA-SW-STT-NOALLOWEDSYNCPOINT    VALUE 'D '.
                15 CAA-LOGON-USERID        PIC X(08).
                15 CAA-SW-PREFORMAT        PIC X(01).
                    88 CAA-SW-PRE-YEPREFORMAT          VALUE 'Y'.
                    88 CAA-SW-PRE-NOPREFORMAT          VALUE 'N'.
      *.MC.S ALINFQA112
      *         15 FILLER                   PIC X(08).
      *         15 CAA-PACKS                PIC X(09).
                15 CAA-SW-FLG-MGCAL        PIC X(1).
                    88 CAA-SW-MGC-NOMAGICALAR          VALUE '0'.
                    88 CAA-SW-MGC-SALEMAGICALARM       VALUE '1'.
                    88 CAA-SW-MGC-THREATMAGICALARM     VALUE '2'.
                    88 CAA-SW-MGC-GRACEPRDMAGICALAR    VALUE '3'.
                15 CAA-SW-FLG-ANLPSBCH     PIC X(03).
                    88 CAA-SW-ANL-PSB                  VALUE 'LIB'.
                    88 CAA-SW-ANL-CHK                  VALUE 'CHE'.
                15 CAA-EXCEPTION-TYPE1     PIC X(04).
                15 CAA-FLG-ANALCHBK        PIC X(05).
                15 CAA-NUM-ANALCHBK        PIC S9(01)V9 COMP-3.
                15 CAA-SW-TYP-ANLCENTE     PIC X(1).
                    88 CAA-SW-ANL-BRNCENT-TYP          VALUE 'O'.
                    88 CAA-SW-ANL-ZONECEN-TYP          VALUE 'Z'.
                    88 CAA-SW-ANL-RISKCENTER-TYP       VALUE 'I'.
                    88 CAA-SW-ANL-REGCENT-TYP          VALUE 'R'.
                15 CAA-SW-ANL-RISKAPRX     PIC X(1).
                    88 CAA-SW-RIS-YESAPRX              VALUE 'S'.
                    88 CAA-SW-RIS-PROPSUBMIT           VALUE 'E'.
      *.MC.E ALINFQA112
      *@FAL0272D-AL0275D-0200
      *OL.S
      *          **---------------------------------------**
      *          **-SALIDA APLIC: DATOS ERROR INESPERADO -**
      *          **---------------------------------------**
      *OL.E
          05 CAA-ERR-INFORMATI.
             10 CAA-OBJECT-ERROR           PIC X(08).
             10 CAA-SQLCODE                PIC S9(09)      COMP.
             10 CAA-SQLERRM                PIC X(70).
             10 CAA-EIBFN                  PIC X(02).
             10 CAA-EIBRSRCE               PIC X(08).
             10 CAA-EIBRCODE               PIC X(06).
             10 CAA-EIBRESP1               PIC S9(09)      COMP.
             10 CAA-EIBRESP2               PIC S9(09)      COMP.
             10 FILLER                     PIC X(30).

      *OL.S
      ******************************************************************
      *         LONGITUD TOTAL DEL REGISTRO EN BYTES :   1225          *
      ******************************************************************
      *OL.E

      *$.
        03 QGECCAA-RE REDEFINES QGECCAA-03.
          05 CAA-DATOS-GRLES.
             10 CAA-ENTIDAD                PIC X(04).
             10 CAA-ENTIDAD-9               REDEFINES CAA-ENTIDAD
                                           PIC 9(04).
             10 CAA-CENTRO-CONT            PIC X(04).
             10 CAA-CENTRO-CONT-9           REDEFINES CAA-CENTRO-CONT
                                           PIC 9(04).
             10 CAA-NETNAME-CONT           PIC X(08).
             10 CAA-TERMINAL-CONT          PIC X(04).
             10 CAA-FECHA-CONT             PIC X(08).
             10 CAA-FECHA-CONT-9            REDEFINES CAA-FECHA-CONT
                                           PIC 9(08).
             10 CAA-FECHA-CONT2            PIC X(10).
             10 CAA-FECHA-CONTED           PIC X(10).
             10 CAA-FECHA-OPER             PIC X(08).
             10 CAA-FECHA-OPER-9            REDEFINES CAA-FECHA-OPER
                                           PIC 9(08).
             10 CAA-FECHA-OPER2            PIC X(10).
             10 CAA-FECHA-OPERED           PIC X(10).
             10 CAA-FECHA-TRANS            PIC X(08).
             10 CAA-FECHA-TRANS-9           REDEFINES CAA-FECHA-TRANS
                                           PIC 9(08).
             10 CAA-FECHA-TRANS2           PIC X(10).
             10 CAA-FECHA-TRANSED          PIC X(10).
             10 CAA-HORA-TRANS             PIC X(06).
             10 CAA-HORA-TRANS-9            REDEFINES CAA-HORA-TRANS
                                           PIC 9(06).
             10 CAA-HORA-TRANSED           PIC X(08).
             10 FILLER                     PIC X(08).
             10 FILLER                     PIC X(04).
             10 FILLER                     PIC X(08).
             10 CAA-SESION                 PIC X(01).
                88 CAA-88-SESION-MANANA                VALUE 'M'.
                88 CAA-88-SESION-TARDE                 VALUE 'T'.
             10 CAA-TIPO-TERM              PIC X(02).
                88 CAA-88-TIPO-TERM-4700               VALUE '11'.
                88 CAA-88-TIPO-TERM-5935               VALUE '12'.
                88 CAA-88-TIPO-TERM-3270               VALUE
             '20', '28', '29'.
                88 CAA-88-TIPO-TERM-PS-1               VALUE '13'.
                88 CAA-88-TIPO-TERM-PS-2               VALUE '14'.
                88 CAA-88-TIPO-TERM-PS-3               VALUE '15'.
                88 CAA-88-TIPO-TERM-PS-4               VALUE '17'.
                88 CAA-88-TIPO-TERM-PS-5               VALUE '18'.
                88 CAA-88-TIPO-TERM-PS-6               VALUE '19' '21'.
                88 CAA-88-TIPO-TERM-ATENEA             VALUE '21'.
                88 CAA-88-TIPO-TERM-PS-8               VALUE '25'.
                88 CAA-88-TIPO-TERM-PS-9               VALUE '26'.
                88 CAA-88-TIPO-TERM-PS                 VALUE '13' '14' '
      -             '15' '16' '17'
             '18' '19' '21' '25' '26'.
                88 CAA-88-TIPO-TERM-VIDEOTEX           VALUE '16'.
                88 CAA-88-TIPO-TERM-UNIV-E             VALUE '35'.
                88 CAA-88-TIPO-TERM-UNIV-S             VALUE '36'.
                88 CAA-88-TIPO-TERM-UNIV               VALUE '35' '36'.
                88 CAA-88-TIPO-TERM-CAJERO             VALUE '40'.
                88 CAA-88-TIPO-TERM-CECA1              VALUE '41'.
                88 CAA-88-TIPO-TERM-CECA2              VALUE '42'.
                88 CAA-88-TIPO-TERM-CECA               VALUE '41' '42'.
                88 CAA-88-TIPO-TERM-TPV                VALUE '43'.
                88 CAA-88-TIPO-TERM-COR-E              VALUE '44'.
                88 CAA-88-TIPO-TERM-COR-S              VALUE '45'.
                88 CAA-88-TIPO-TERM-COR-P              VALUE '52'.
                88 CAA-88-TIPO-TERM-CORONA             VALUE
             '44' '45' '52'.
                88 CAA-88-TIPO-TERM-SEMP-AE            VALUE '46'.
                88 CAA-88-TIPO-TERM-SEMP-AA            VALUE '47'.
                88 CAA-88-TIPO-TERM-SEMP-RF            VALUE '48'.
                88 CAA-88-TIPO-TERM-SEMP-AF            VALUE '49'.
                88 CAA-88-TIPO-TERM-SEMP-F             VALUE '50'.
                88 CAA-88-TIPO-TERM-SEMP
                                   VALUE '46' '47' '48' '49' '50'.
                88 CAA-88-TIPO-TERM-ENTRADA            VALUE '53'.
                88 CAA-88-TIPO-TERM-4B-REAL            VALUE '54'.
                88 CAA-88-TIPO-TERM-4B-FIC             VALUE '55'.
                88 CAA-88-TIPO-TERM-4B                 VALUE '54' '55'.
                88 CAA-88-TIPO-TERM-LINK24-A           VALUE '56'.
                88 CAA-88-TIPO-TERM-LINK24-P           VALUE '57'.
                88 CAA-88-TIPO-TERM-LINK24-E           VALUE '58'.
                88 CAA-88-TIPO-TERM-LINK24-O           VALUE '59'.
                88 CAA-88-TIPO-TERM-LINK24             VALUE
             '56' '57' '58' '59'.
                88 CAA-88-TIPO-TERMINAL-TAVE           VALUE '60'.
                88 CAA-88-TIPO-TERM-POLCARD-I          VALUE '61'.
                88 CAA-88-TIPO-TERM-POLCARD-V          VALUE '62'.
                88 CAA-88-TIPO-TERM-POLCARD-O          VALUE '63'.
                88 CAA-88-TIPO-TERM-POLCARD            VALUE
             '61' '62' '63'.

                88 CAA-88-TIPO-TERM-CENTROAUT
                                   VALUE '40' '41' '42' '43' '44'
             '45' '46' '47' '48' '49'
             '50' '52' '53' '54' '55'
             '35' '36'
             '60'
             '56' '57' '58' '59'
             '61' '62' '63'.
             10 FILLER                     PIC X(04).
             10 CAA-CODTRAN                PIC X(04).
             10 CAA-TIPO-PROCESO           PIC X(01).
                88 CAA-88-TIPO-PROCESO-ONLI            VALUE 'O'.
                88 CAA-88-TIPO-PROCESO-AUTO            VALUE 'A'.
                88 CAA-88-TIPO-PROCESO-TELE            VALUE 'T'.
                88 CAA-88-TIPO-PROCESO-OFF             VALUE 'F'.
             10 CAA-ESTADO-APLIC           PIC X(01).
                88 CAA-88-ACTIVA                       VALUE 'A'.
                88 CAA-88-DESACTIVA                    VALUE 'D'.
                88 CAA-88-CAMBIO-SESION                VALUE 'C'.
                88 CAA-88-RECUPERACION                 VALUE 'R'.
             10 CAA-NUM-REINTENTOS         PIC S9(4) COMP.
             10 CAA-NUM-SECUE              PIC X(05).
             10 CAA-NUM-SECUE-9  REDEFINES CAA-NUM-SECUE
                                           PIC 9(05).
             10 CAA-VERSION-GAT            PIC X(04).
             10 CAA-IDIOMA-TERM            PIC X(01).
                88 CAA-88-IDITERM-NADA                 VALUE ' '.
                88 CAA-88-IDITERM-ESP                  VALUE 'E'.
                88 CAA-88-IDITERM-CAT                  VALUE 'C'.
                88 CAA-88-IDITERM-GAL                  VALUE 'G'.
                88 CAA-88-IDITERM-ING                  VALUE 'I'.
                88 CAA-88-IDITERM-FRA                  VALUE 'F'.
                88 CAA-88-IDITERM-POL                  VALUE 'P'.
             10 CAA-STATUS-APLIC           PIC X(01).
                88 CAA-88-STATUS-N                     VALUE 'N'.
                88 CAA-88-STATUS-C                     VALUE 'C'.
                88 CAA-88-STATUS-E                     VALUE 'E'.
                88 CAA-88-STATUS-B                     VALUE 'B'.
                88 CAA-88-STATUS-S                     VALUE 'S'.
                88 CAA-88-STATUS-M                     VALUE 'M'.
                88 CAA-88-STATUS-X                     VALUE 'X'.
             10 CAA-MODELO-TERM            PIC X(02).
                88 CAA-88-MODELO-INTERNET              VALUE 'IN'.
                88 CAA-88-MODELO-MUSEOS                VALUE 'MU'.
                88 CAA-88-MODELO-ACTUALIZ              VALUE 'AC'.
                88 CAA-88-MODELO-TELEFONO              VALUE 'TE'.
             10 FILLER                     PIC X(02).
             10 CAA-CODTRAN-MULT           PIC X(4).
             10 FILLER                     PIC X(09).
          05 CAA-ENTRADA-TERM.
             10 CAA-TECLA                  PIC X(02).
             10 CAA-CAJERO                 PIC X(01).
                88 CAA-88-CAJERO-A                     VALUE 'A'.
                88 CAA-88-CAJERO-B                     VALUE 'B'.
             10 CAA-MOD-TAG                PIC X(01).
                88 CAA-88-MOD-TAG-SI                   VALUE 'S'.
                88 CAA-88-MOD-TAG-NO                   VALUE 'N'.
                88 CAA-88-MOD-TAG-NADA                 VALUE ' '.
             10 CAA-PTR-COPYIN              POINTER.
             10 CAA-PAPEL                  PIC X(1).
                88 CAA-88-PAPEL-SI                     VALUE 'S'.
                88 CAA-88-PAPEL-NO                     VALUE 'N'.
             10 CAA-DIVISA-ENT             PIC X(03).
             10 CAA-TYPE-INPUT             PIC X(01).
                       88 CAA-88-TYPE-BMS              VALUE 'B'.
                       88 CAA-88-TYPE-COPY             VALUE 'C' 'G'.
                       88 CAA-88-TYPE-COPY-MENOS2K     VALUE 'C'.
                       88 CAA-88-TYPE-COPY-MAS2K       VALUE 'G'.
             10 FILLER                     PIC X(05).
          05 CAA-AUTORIZACION.
             10 CAA-AUTORIZ                PIC X(0150).
             10 CAA-AUTORIZ-O               REDEFINES CAA-AUTORIZ
                                            OCCURS 10 TIMES.
                15 CAA-CODERR-AUT          PIC X(07).
                15 CAA-SITUACION-AUT       PIC X(08).
             10 CAA-IND-AUTO               PIC X(01).
                88 CAA-88-IND-AUTO-SI                  VALUE 'S'.
                88 CAA-88-IND-AUTO-NO                  VALUE 'N' ' '.
             10 CAA-IMPORTE-AUTO           PIC S9(13)      COMP-3.
             10 CAA-REFER-AUTO             PIC X(20).
             10 CAA-ERROR-AUTO-ALT         PIC X(1).
                88 CAA-88-ERROR-AUTO-ALT-SI            VALUE 'S'.
             10 FILLER                     PIC X(21).
          05 CAA-AUTORIZACION-AUX.
             10 CAA-NUMSEQ                 PIC S9(07) COMP-3.
             10 CAA-NUMSEQ-R                REDEFINES  CAA-NUMSEQ
                                           PIC X(04).
             10 CAA-PTR-CUA                 POINTER.
             10 CAA-PTR-CUA-R               REDEFINES CAA-PTR-CUA
                                           PIC X(04).
          05 FILLER.
             10 CAA-ESTADO                 PIC X(01).
                88 CAA-88-ESTADO-INICIO                VALUE 'I'.
                88 CAA-88-ESTADO-CONTIN                VALUE 'C'.
                88 CAA-88-ESTADO-CONFIR                VALUE 'X'.
             10 CAA-CASO                   PIC X(01).
             10 CAA-DATOS                  PIC X(30).
             10 CAA-DATOS-RED     REDEFINES CAA-DATOS.
                15 FILLER                  PIC X(11).
                15 CAA-LISTADO-DIN.
                   20 CAA-IDTABLA          PIC X(10).
                   20 CAA-POSICION-COM     PIC 9(4).
                   20 CAA-LONGITUD-COM     PIC 9(4).
                   20 CAA-IDIOMA-TABLA     PIC X(1).
             10 CAA-LONDATA                PIC S9(05)      COMP-3.
             10 CAA-PTRDATA                 POINTER.
             10 CAA-RED-EXTERNA            PIC X(1).
                88 CAA-88-RED-EXTERNA                  VALUE 'S'.
             10 CAA-PTR-MEN-INT             POINTER.
             10 CAA-PTR-MEN-INT-H
                        REDEFINES  CAA-PTR-MEN-INT
                                           PIC X(4).
                88 CAA-88-PTR-MEN-VACIO                VALUE
                    HIGH-VALUES.
             10 CAA-PTR-NOARQ               POINTER.
             10 FILLER                     PIC X(01).
          05 CAA-PROXIMA-TRN.
             10 CAA-CODTRAN-SIG            PIC X(04).
                88 CAA-88-CODTRAN-SIG-ULTI             VALUE 'ULTI'.
                88 CAA-88-CODTRAN-SIG-SAME             VALUE 'SAME'.
                88 CAA-88-CODTRAN-SIG-MENU             VALUE 'MENU'.
                88 CAA-88-CODTRAN-SIG-VACIO            VALUE SPACES.
             10 CAA-AUTOMATICA             PIC X(01).
                88 CAA-88-AUTOMATICA-SI                VALUE 'S'.
                88 CAA-88-AUTOMATICA-NO                VALUE 'N' ' '.
             10 CAA-ACCION                 PIC X(03).
                88 CAA-88-ACCION-PROGRAMA              VALUE 'PRG'.
                88 CAA-88-ACCION-TERMINAL              VALUE
             'TER', '   '.
             10 CAA-CADENA                 PIC X(01).
                88 CAA-88-CADENA-INICIO                VALUE 'I'.
                88 CAA-88-CADENA-ANADIR                VALUE 'A'.
             10 CAA-CASO-CAD               PIC X(01).
             10 CAA-DATOS-CAD              PIC X(30).
          05 CAA-SALIDA-TERM.
             10 CAA-COD-ERROR              PIC X(07).
                88 CAA-88-COD-ERROR-VACIO              VALUE SPACES.
             10 CAA-COD-AVISO1             PIC X(07).
                88 CAA-88-COD-AVISO1-VACIO             VALUE SPACES.
             10 CAA-COD-AVISO2             PIC X(07).
                88 CAA-88-COD-AVISO2-VACIO             VALUE SPACES.
             10 CAA-VAR1-ERROR             PIC X(20).
             10 CAA-VAR2-ERROR             PIC X(20).
             10 CAA-VAR1-AVISO1            PIC X(20).
             10 CAA-VAR2-AVISO1            PIC X(20).
             10 CAA-VAR1-AVISO2            PIC X(20).
             10 CAA-VAR2-AVISO2            PIC X(20).
             10 CAA-IMPORTE-DISP           PIC S9(13)      COMP-3.
             10 CAA-DIARIO-LOCAL           PIC X(80).
             10 CAA-TIPO-SALIDA            PIC X(01).
                88 CAA-88-TIPO-SALIDA-ENT              VALUE 'E'.
                88 CAA-88-TIPO-SALIDA-SAL              VALUE 'S'.
                88 CAA-88-TIPO-SALIDA-PAG              VALUE 'P'.
                88 CAA-88-TIPO-SALIDA-COPY             VALUE 'C'.
                88 CAA-88-TIPO-SALIDA-NO               VALUE ' '.
             10 CAA-COPY-OUT               PIC X(08).
             10 CAA-PANEL-OUT              PIC X(08).
             10 CAA-DESTINOS               PIC X(0075).
             10 CAA-DESTINOS-O              REDEFINES CAA-DESTINOS
                                            OCCURS 5  TIMES.
                15 CAA-DESTINO             PIC X(04).
                15 CAA-IND-PANDOC          PIC X(01).
                15 CAA-NUM-DOCUM           PIC X(01).
                15 CAA-PRILIN-DOCUM        PIC X(02).
                15 CAA-PRILIN-DOCUM-9       REDEFINES CAA-PRILIN-DOCUM
                                           PIC 9(02).
                15 CAA-IMPRESO             PIC X(06).
                15 CAA-DISCO-PS REDEFINES CAA-IMPRESO.
                   20 CAA-NOM-FICHERO-HD   PIC X(5).
                   20 CAA-USO-FICHERO-HD   PIC X.
                15 CAA-IDIOMA              PIC X(01).
          05 CAA-PAGINAR.
             10 CAA-CONTENID               PIC X(50).
             10 CAA-SELEC-PERMIT           PIC X(0010).
             10 CAA-SELEC-PERMIT-O          REDEFINES CAA-SELEC-PERMIT
                                            OCCURS 10 TIMES.
                15 CAA-SEL-PERMIT          PIC X(01).
             10 CAA-IND-VARSEL             PIC X(01).
                88 CAA-88-IND-VARSEL-SI                VALUE 'S'.
                88 CAA-88-IND-VARSEL-NO                VALUE 'N'.
             10 CAA-MARGEN-FIJO            PIC X(02).
             10 CAA-MARGEN-FIJO-9           REDEFINES CAA-MARGEN-FIJO
                                           PIC 9(02).
             10 CAA-FKEY                   PIC X(0072).
             10 CAA-FKEY-O                  REDEFINES CAA-FKEY
                                            OCCURS 8  TIMES.
                15 CAA-FKEY-NUM            PIC X(02).
                15 CAA-FKEY-LIT            PIC X(06).
                15 CAA-FKEY-SEL            PIC X(01).
             10 CAA-IND-AVPAG              PIC X(01).
                88 CAA-88-IND-AVPAG-SI                 VALUE 'S'.
                88 CAA-88-IND-AVPAG-NO                 VALUE 'N' ' '.
             10 CAA-IND-MOD-DATO           PIC X(01).
                88 CAA-88-IND-MOD-DATO-SI              VALUE 'S'.
                88 CAA-88-IND-MOD-DATO-NO              VALUE 'N'.
             10 CAA-LINEA-PANT             PIC S9(05)      COMP-3.
             10 CAA-COLUM-PANT             PIC S9(05)      COMP-3.
             10 CAA-NUM-LIN-CAB            PIC X(02).
             10 CAA-NUM-LIN-CAB-9  REDEFINES CAA-NUM-LIN-CAB
                                           PIC 9(02).
             10 CAA-IND-SCROLL-LAT         PIC X(01).
                88 CAA-88-IND-SCROLL-SI                VALUE 'S' ' '.
                88 CAA-88-IND-SCROLL-NO                VALUE 'N'.
             10 CAA-NUM-ITEM-SELEC         PIC S9(05)    COMP-3.
             10 CAA-MAX-LISTAR             PIC S9(04)    COMP.
             10 CAA-IND-VAR-HEADER         PIC X(01).
                88 CAA-88-IND-VAR-HEA-SI               VALUE 'S'.
                88 CAA-88-IND-VAR-HEA-NO               VALUE 'N' ' '.
             10 CAA-COPYOUT-GTS            PIC X(8).
          05 FILLER.
             10 FILLER                     PIC X(1).
             10 FILLER                     PIC X(1).
             10 FILLER                     PIC X(4).
          05 CAA-ANALITICA.
             10 CAA-ENTIDAD-ANA            PIC X(04).
             10 CAA-ENTIDAD-ANA-9           REDEFINES CAA-ENTIDAD-ANA
                                           PIC 9(04).
             10 CAA-CENTRO-ANA             PIC X(04).
             10 CAA-CENTRO-ANA-9            REDEFINES CAA-CENTRO-ANA
                                           PIC 9(04).
             10 CAA-PRODUCTO-ANA           PIC X(20).
             10 CAA-PRODUCTO-ANA-R REDEFINES CAA-PRODUCTO-ANA.
                15 CAA-NUMECTA-ANA         PIC X(16).
                15 CAA-CODISER-ANA         PIC X(02).
                15 FILLER                  PIC X(02).
             10 CAA-ANALITIC1-GRUPO.
                15 CAA-CLIENTE-ANA         PIC X(08).
                15 CAA-IMPORTE-ANA         PIC S9(13)V9(2) COMP-3.
                15 CAA-SUBPROD-ANA         PIC X(04).
                15 CAA-FINALID-ANA         PIC X(03).
                15 CAA-GARANTIA-ANA        PIC X(01).
                15 CAA-SUB-CLASIF          PIC X(03).
             10 CAA-ANALITICA-1  REDEFINES CAA-ANALITIC1-GRUPO
                                           PIC X(27).
             10 CAA-TIOPER                 PIC X(01).
                88 CAA-88-TIOPER-ALTA                  VALUE 'A'.
                88 CAA-88-TIOPER-BAJA                  VALUE 'B'.
                88 CAA-88-TIOPER-MODIF                 VALUE 'M'.
                88 CAA-88-TIOPER-CONSULTA              VALUE 'C'.
                88 CAA-88-TIOPER-EDICION               VALUE 'E'.
                88 CAA-88-TIOPER-PETICION              VALUE 'P'.
                88 CAA-88-TIOPER-ENTSAL                VALUE 'O'.
                88 CAA-88-TIOPER-NADA                  VALUE 'N'.
                88 CAA-88-TIOPER-TRAN-TAF              VALUE '1'.
                88 CAA-88-TIOPER-TRAN-SICA             VALUE '2'.
                88 CAA-88-TIOPER-TRAN-PERI             VALUE '3'.
                88 CAA-88-TIOPER-TRAN-CONS             VALUE '4'.
                88 CAA-88-TIOPER-TRAN-ANUL             VALUE '5'.
                88 CAA-88-TIOPER-CANC                  VALUE '6'.
             10 CAA-CONTABLE               PIC X(01).
                88 CAA-88-CONTABLE-SI                  VALUE 'S'.
                88 CAA-88-CONTABLE-NO                  VALUE 'N'.
             10 CAA-DATOS-APLIC            PIC X(20).
             10 CAA-ANALITICA-2            PIC X(30).
             10 CAA-AREA-ALTAMIRA-II        REDEFINES CAA-ANALITICA-2.
                15 CAA-CANAL               PIC X(02).
                15 CAA-STARTCODE           PIC X(02).
                   88 CAA-88-DPL-NO-SYNC               VALUE 'D '.
                   88 CAA-88-DPL-SI-SYNC               VALUE 'DS'.
                   88 CAA-88-DPL                       VALUE 'D ' 'DS'.
                   88 CAA-88-COLA-TD                   VALUE 'QD'.
                   88 CAA-88-START-SIN-DATOS           VALUE 'S '.
                   88 CAA-88-START-CON-DATOS           VALUE 'SD'.
                   88 CAA-88-FEPI                      VALUE 'SZ'.
                   88 CAA-88-TERMINAL                  VALUE 'TD'.
                   88 CAA-88-SYNCPOINT-PERMITIDO       VALUE
             'DS' 'QD' 'S ' 'SD' 'SZ' 'TD'.
                   88 CAA-88-SYNCPOINT-NO-PERMITIDO    VALUE 'D '.
                15 CAA-USERID-LOGON        PIC X(08).
                15 CAA-PREFORMATEAR        PIC X(01).
                    88 CAA-88-PREFORMATEAR-SI          VALUE 'Y'.
                    88 CAA-88-PREFORMATEAR-NO          VALUE 'N'.
                15 CAA-ALARMA-MAGIC        PIC X(1).
                    88 CAA-88-ALARMA-MAGIC-NO          VALUE '0'.
                    88 CAA-88-ALARMA-MAGIC-VENTA       VALUE '1'.
                    88 CAA-88-ALARMA-MAGIC-AMENAZA     VALUE '2'.
                    88 CAA-88-ALARMA-MAGIC-CARENCIA    VALUE '3'.
                15 CAA-IND-LIB-CHE-ANA     PIC X(03).
                    88 CAA-88-LIB-ANA                  VALUE 'LIB'.
                    88 CAA-88-CHE-ANA                  VALUE 'CHE'.
                15 CAA-TIPO-INCIDENCIA     PIC X(04).
                15 CAA-SMYTALON-ANA        PIC X(05).
                15 CAA-SMNTALON-ANA        PIC S9(01)V9 COMP-3.
                15 CAA-TIPO-CENTRO-ANA     PIC X(1).
                    88 CAA-88-TIPO-CENTRO-OFI          VALUE 'O'.
                    88 CAA-88-TIPO-CENTRO-ZON          VALUE 'Z'.
                    88 CAA-88-TIPO-CENTRO-RIESGO       VALUE 'I'.
                    88 CAA-88-TIPO-CENTRO-REG          VALUE 'R'.
                15 CAA-APRO-RIESGO-ANA     PIC X(1).
                    88 CAA-88-APRO-RIESGO              VALUE 'S'.
                    88 CAA-88-ELEV-PROPUESTA           VALUE 'E'.
          05 CAA-INFORMA-ERROR.
             10 CAA-OBJETO-ERROR           PIC X(08).
             10 FILLER                     PIC S9(09)      COMP.
             10 FILLER                     PIC X(70).
             10 FILLER                     PIC X(02).
             10 FILLER                     PIC X(08).
             10 FILLER                     PIC X(06).
             10 FILLER                     PIC S9(09)      COMP.
             10 FILLER                     PIC S9(09)      COMP.
             10 FILLER                     PIC X(30).

